/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config/{overlay_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config__overlay_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/raw_config/{overlay_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Raw Config */
        get: operations["get_raw_config_api_raw_config__overlay_id__get"];
        put?: never;
        /** Set Raw Config */
        post: operations["set_raw_config_api_raw_config__overlay_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state/{overlay_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update State */
        post: operations["update_state_api_state__overlay_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/theme/{overlay_id}/{theme_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Theme */
        post: operations["apply_theme_api_theme__overlay_id___theme_name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Themes */
        get: operations["list_themes_api_themes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/_log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Client Log
         * @description Accept a frontend error report. Returns 429 (empty body) when
         *     rate-limited so well-behaved clients back off without sendBeacon
         *     surfacing a JSON error payload.
         */
        post: operations["post_client_log_api_v1__log_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/custom-overlays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Custom Overlays
         * @description Return every custom overlay persisted on disk.
         *
         *     Each entry carries the overlay id (used directly as the OID) and its
         *     derived output key.
         */
        get: operations["list_custom_overlays_api_v1_admin_custom_overlays_get"];
        put?: never;
        /**
         * Create Custom Overlay
         * @description Create a new custom overlay, optionally cloning an existing one.
         */
        post: operations["create_custom_overlay_api_v1_admin_custom_overlays_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/custom-overlays/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Custom Overlay
         * @description Remove a custom overlay and its persisted state.
         */
        delete: operations["delete_custom_overlay_api_v1_admin_custom_overlays__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Login
         * @description Validate the admin password. Returns ``{"ok": true}`` on success.
         */
        post: operations["admin_login_api_v1_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Status
         * @description Report whether overlay management is enabled on this server.
         */
        get: operations["admin_status_api_v1_admin_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * App Config
         * @description Return runtime app configuration consumed by the SPA on boot.
         */
        get: operations["app_config_api_v1_app_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent action audit log
         * @description Return up to *limit* most-recent records from the action log.
         *
         *     Records are ordered chronologically (oldest first within the
         *     returned window). Each entry has the shape::
         *
         *         {"ts": 1714508400.123,
         *          "action": "add_point",
         *          "params": {"team": 1, "undo": false},
         *          "result": {"current_set": 2, "team_1": {...}, ...}}
         */
        get: operations["get_audit_log_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Customization */
        get: operations["get_customization_api_v1_customization_get"];
        /** Update Customization */
        put: operations["update_customization_api_v1_customization_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/display/simple-mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Simple Mode */
        post: operations["set_simple_mode_api_v1_display_simple_mode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/display/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Visibility */
        post: operations["set_visibility_api_v1_display_visibility_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game/add-point": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Point */
        post: operations["add_point_api_v1_game_add_point_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game/add-set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Set */
        post: operations["add_set_api_v1_game_add_set_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game/add-timeout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Timeout */
        post: operations["add_timeout_api_v1_game_add_timeout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game/change-serve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Serve */
        post: operations["change_serve_api_v1_game_change_serve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Game */
        post: operations["reset_game_api_v1_game_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game/set-score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Score */
        post: operations["set_score_api_v1_game_set_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game/set-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Sets */
        post: operations["set_sets_api_v1_game_set_sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game/start-match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Arm the match-start timer without scoring a point
         * @description Stamps ``match_started_at`` with the current wallclock if the
         *     match isn't already armed. Idempotent — a second call leaves the
         *     original anchor in place. The HUD timer / report duration / undo
         *     flow all read this field downstream.
         */
        post: operations["start_match_api_v1_game_start_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reverse the most recent undoable action
         * @description Pops the most recent forward ``add_point`` / ``add_set`` /
         *     ``add_timeout`` from the audit log and applies the inverse via
         *     ``undo=True``. Returns ``success=false`` with message
         *     ``"Nothing to undo."`` when the log has no eligible entry.
         */
        post: operations["undo_last_api_v1_game_undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Links
         * @description Return control, overlay, and preview links for the session.
         */
        get: operations["get_links_api_v1_links_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List archived matches
         * @description Return summaries of archived matches, newest first.
         *
         *     Each entry is enough to render a list view: ``match_id``, ``oid``,
         *     ``ended_at``, ``duration_s``, ``winning_team``, plus the team-level
         *     sets-won and ``current_set``. Use ``GET /matches/{match_id}`` for
         *     the full snapshot including the audit log and customization.
         */
        get: operations["list_matches_api_v1_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full archived match snapshot */
        get: operations["get_match_api_v1_matches__match_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overlays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Overlays
         * @description Return predefined overlays available for selection.
         *
         *     Sourced exclusively from the ``PREDEFINED_OVERLAYS`` environment
         *     variable (also populated via the remote configurator). Entries are
         *     filtered by ``allowed_users`` using the caller's identity when user
         *     authentication is enabled.
         */
        get: operations["get_overlays_api_v1_overlays_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Init Session
         * @description Initialise (or re-use) a game session for the given overlay ID.
         */
        post: operations["init_session_api_v1_session_init_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update match rules (mode, points, sets) for the session
         * @description Update match-rule preset for the session.
         *
         *     All fields are optional. ``mode`` accepts ``"indoor"`` or
         *     ``"beach"`` and drives the beach side-switch indicator. The
         *     ``reset_to_defaults`` flag replaces every limit with the
         *     canonical preset for the resulting mode. Per-field overrides
         *     in the same call still win, so the UI can switch modes and
         *     keep one custom limit in a single request.
         */
        post: operations["set_rules_api_v1_session_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_api_v1_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/styles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Styles
         * @description Return available overlay styles.
         */
        get: operations["get_styles_api_v1_styles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Teams
         * @description Return predefined team names with icon/color data.
         */
        get: operations["get_teams_api_v1_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Themes
         * @description Return available theme definitions.
         */
        get: operations["get_themes_api_v1_themes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create/overlay/{overlay_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Create Overlay */
        get: operations["create_overlay_create_overlay__overlay_id__get_post"];
        put?: never;
        /** Create Overlay */
        post: operations["create_overlay_create_overlay__overlay_id__get_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delete/overlay/{overlay_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Delete Overlay */
        get: operations["delete_overlay_delete_overlay__overlay_id__delete_get_post"];
        put?: never;
        /** Delete Overlay */
        post: operations["delete_overlay_delete_overlay__overlay_id__delete_get_post"];
        /** Delete Overlay */
        delete: operations["delete_overlay_delete_overlay__overlay_id__delete_get_post"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/list/overlay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Overlays
         * @description Return every overlay id plus its output key.
         *
         *     Gated behind ``OVERLAY_MANAGER_PASSWORD`` because the response
         *     defeats the capability-URL design of ``/overlay/{output_key}``.
         *     See ``AUTHENTICATION.md`` (F-4).
         */
        get: operations["list_overlays_list_overlay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manifest.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve Manifest */
        get: operations["serve_manifest_manifest_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manifest.webmanifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve Webmanifest */
        get: operations["serve_webmanifest_manifest_webmanifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match/{match_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Print-friendly HTML report for an archived match */
        get: operations["match_report_match__match_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/index.html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browseable HTML list of archived matches for an OID */
        get: operations["matches_index_matches_index_html_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an archived match snapshot
         * @description Delete a single archived match by id.
         *
         *     Requires a valid admin token unless ``MATCH_REPORT_PUBLIC_DELETE``
         *     is set — that flag is independent from ``MATCH_REPORT_PUBLIC``
         *     (public read does *not* imply public delete) and lets operators
         *     expose the per-row Delete button on the matches index without
         *     sharing the admin password. Returns 204 on success, 404 when the
         *     match does not exist, and 401/403/503 for the various
         *     authentication failure modes when the flag is off.
         */
        delete: operations["delete_archived_match_matches__match_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overlay/{overlay_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve Overlay */
        get: operations["serve_overlay_overlay__overlay_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sw.js": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve Sw */
        get: operations["serve_sw_sw_js_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionResponse */
        ActionResponse: {
            /** Message */
            message?: string | null;
            state?: components["schemas"]["GameStateResponse"] | null;
            /** Success */
            success: boolean;
        };
        /** AppConfigResponse */
        AppConfigResponse: {
            /** Title */
            title: string;
        };
        /**
         * BeachSideSwitch
         * @description Beach volleyball side-switch indicator (only set when mode='beach').
         *
         *     Sides switch every 7 combined points in non-tiebreak sets and
         *     every 5 in the tiebreak. ``is_switch_pending`` is true the moment
         *     a point crosses a boundary — operators should swap teams now.
         */
        BeachSideSwitch: {
            /** Interval */
            interval: number;
            /** Is Switch Pending */
            is_switch_pending: boolean;
            /** Next Switch At */
            next_switch_at: number;
            /** Points In Set */
            points_in_set: number;
            /** Points Until Switch */
            points_until_switch: number;
        };
        /** ClientLogRecord */
        ClientLogRecord: {
            /** Href */
            href?: string | null;
            /**
             * Level
             * @default error
             * @enum {string}
             */
            level: "error" | "warn";
            /** Message */
            message: string;
            /** Oid */
            oid?: string | null;
            /** Stack */
            stack?: string | null;
            /** User Agent */
            user_agent?: string | null;
        };
        /** CustomOverlayCreate */
        CustomOverlayCreate: {
            /**
             * Copy From
             * @description Optional existing overlay id to clone configuration from
             */
            copy_from?: string | null;
            /**
             * Name
             * @description Overlay id used as OID
             */
            name: string;
        };
        /** GameStateResponse */
        GameStateResponse: {
            beach_side_switch?: components["schemas"]["BeachSideSwitch"] | null;
            /**
             * Can Undo
             * @default false
             */
            can_undo: boolean;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Current Set */
            current_set: number;
            /** Match Finished */
            match_finished: boolean;
            match_point_info?: components["schemas"]["MatchPointInfo"] | null;
            /** Match Started At */
            match_started_at?: number | null;
            /** Serve */
            serve: string;
            /** Simple Mode */
            simple_mode: boolean;
            team_1: components["schemas"]["TeamState"];
            team_2: components["schemas"]["TeamState"];
            /** Visible */
            visible: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InitRequest */
        InitRequest: {
            /** Oid */
            oid: string;
            /** Output Url */
            output_url?: string | null;
            /** Points Limit */
            points_limit?: number | null;
            /** Points Limit Last Set */
            points_limit_last_set?: number | null;
            /** Sets Limit */
            sets_limit?: number | null;
        };
        /** MatchInfoModel */
        MatchInfoModel: {
            /** Best Of Sets */
            best_of_sets?: number | null;
            /** Current Set */
            current_set?: number | null;
            /** Phase */
            phase?: string | null;
            /** Show Only Current Set */
            show_only_current_set?: boolean | null;
            /** Tournament */
            tournament?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * MatchPointInfo
         * @description Per-team flags signalling that the next point would close out the
         *     current set or the entire match.
         *
         *     Match point implies set point. The renderer is expected to show only
         *     the more specific label (match point) when both apply. All flags
         *     collapse to ``False`` once ``match_finished`` is true.
         */
        MatchPointInfo: {
            /** Team 1 Match Point */
            team_1_match_point: boolean;
            /** Team 1 Set Point */
            team_1_set_point: boolean;
            /** Team 2 Match Point */
            team_2_match_point: boolean;
            /** Team 2 Set Point */
            team_2_set_point: boolean;
        };
        /** OverlayControlModel */
        OverlayControlModel: {
            /** Colors */
            colors?: {
                [key: string]: string;
            } | null;
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
            /** Player Stats Data */
            player_stats_data?: unknown | null;
            /** Preferredstyle */
            preferredStyle?: string | null;
            /** Show Bottom Ticker */
            show_bottom_ticker?: boolean | null;
            /** Show Main Scoreboard */
            show_main_scoreboard?: boolean | null;
            /** Show Player Stats */
            show_player_stats?: boolean | null;
            /** Ticker Message */
            ticker_message?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * OverlayPayload
         * @description Predefined overlay entry returned by ``GET /overlays``.
         */
        OverlayPayload: {
            /**
             * Name
             * @description Display name of the overlay
             */
            name: string;
            /**
             * Oid
             * @description Overlay identifier
             */
            oid: string;
        };
        /** OverlayStateUpdate */
        OverlayStateUpdate: {
            match_info?: components["schemas"]["MatchInfoModel"] | null;
            overlay_control?: components["schemas"]["OverlayControlModel"] | null;
            /** Raw Remote Customization */
            raw_remote_customization?: unknown | null;
            /** Raw Remote Model */
            raw_remote_model?: unknown | null;
            team_away?: components["schemas"]["TeamStateModel"] | null;
            team_home?: components["schemas"]["TeamStateModel"] | null;
        } & {
            [key: string]: unknown;
        };
        /** RawConfigPayload */
        RawConfigPayload: {
            /** Customization */
            customization?: unknown | null;
            /** Model */
            model?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /** ServeRequest */
        ServeRequest: {
            /**
             * Team
             * @enum {integer}
             */
            team: 1 | 2;
        };
        /**
         * SetRulesRequest
         * @description Body for ``POST /api/v1/session/rules``.
         *
         *     All fields are optional. ``mode`` switches between ``"indoor"``
         *     and ``"beach"``; ``reset_to_defaults`` replaces every limit with
         *     the canonical preset for the resulting mode (per-field overrides
         *     in the same call still win).
         */
        SetRulesRequest: {
            /** Mode */
            mode?: ("indoor" | "beach") | null;
            /** Points Limit */
            points_limit?: number | null;
            /** Points Limit Last Set */
            points_limit_last_set?: number | null;
            /**
             * Reset To Defaults
             * @default false
             */
            reset_to_defaults: boolean;
            /** Sets Limit */
            sets_limit?: number | null;
        };
        /** SetScoreRequest */
        SetScoreRequest: {
            /** Set Number */
            set_number: number;
            /**
             * Team
             * @enum {integer}
             */
            team: 1 | 2;
            /** Value */
            value: number;
        };
        /** SetSetsRequest */
        SetSetsRequest: {
            /**
             * Team
             * @enum {integer}
             */
            team: 1 | 2;
            /** Value */
            value: number;
        };
        /** SimpleModeRequest */
        SimpleModeRequest: {
            /** Enabled */
            enabled: boolean;
        };
        /** TeamActionRequest */
        TeamActionRequest: {
            /**
             * Team
             * @enum {integer}
             */
            team: 1 | 2;
            /**
             * Undo
             * @default false
             */
            undo: boolean;
        };
        /** TeamState */
        TeamState: {
            /** Scores */
            scores: {
                [key: string]: unknown;
            };
            /** Serving */
            serving: boolean;
            /** Sets */
            sets: number;
            /** Timeouts */
            timeouts: number;
        };
        /** TeamStateModel */
        TeamStateModel: {
            /** Color Primary */
            color_primary?: string | null;
            /** Color Secondary */
            color_secondary?: string | null;
            /** Logo Url */
            logo_url?: string | null;
            /** Name */
            name?: string | null;
            /** Points */
            points?: number | null;
            /** Serving */
            serving?: boolean | null;
            /** Set History */
            set_history?: {
                [key: string]: number;
            } | null;
            /** Sets Won */
            sets_won?: number | null;
            /** Short Name */
            short_name?: string | null;
            /** Timeouts Taken */
            timeouts_taken?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VisibilityRequest */
        VisibilityRequest: {
            /** Visible */
            visible: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config_api_config__overlay_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                overlay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_raw_config_api_raw_config__overlay_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                overlay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_raw_config_api_raw_config__overlay_id__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                overlay_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RawConfigPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_state_api_state__overlay_id__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                overlay_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverlayStateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_theme_api_theme__overlay_id___theme_name__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                overlay_id: string;
                theme_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_themes_api_themes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    post_client_log_api_v1__log_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientLogRecord"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_custom_overlays_api_v1_admin_custom_overlays_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_custom_overlay_api_v1_admin_custom_overlays_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomOverlayCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_custom_overlay_api_v1_admin_custom_overlays__name__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_login_api_v1_admin_login_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_status_api_v1_admin_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    app_config_api_v1_app_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfigResponse"];
                };
            };
        };
    };
    get_audit_log_api_v1_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_v1_config_get: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customization_api_v1_customization_get: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_customization_api_v1_customization_put: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_simple_mode_api_v1_display_simple_mode_post: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimpleModeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_visibility_api_v1_display_visibility_post: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisibilityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_point_api_v1_game_add_point_post: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_set_api_v1_game_add_set_post: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_timeout_api_v1_game_add_timeout_post: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_serve_api_v1_game_change_serve_post: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_game_api_v1_game_reset_post: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_score_api_v1_game_set_score_post: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_sets_api_v1_game_set_sets_post: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSetsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_match_api_v1_game_start_match_post: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_last_api_v1_game_undo_post: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_links_api_v1_links_get: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_api_v1_matches_get: {
        parameters: {
            query?: {
                /** @description Filter to a single OID */
                oid?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_api_v1_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overlays_api_v1_overlays_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverlayPayload"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    init_session_api_v1_session_init_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_rules_api_v1_session_rules_post: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRulesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_api_v1_state_get: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_styles_api_v1_styles_get: {
        parameters: {
            query?: {
                /** @description Overlay ID */
                oid?: string | null;
                /** @description Alias of `oid` for backward compatibility */
                control?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_teams_api_v1_teams_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_themes_api_v1_themes_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_overlay_create_overlay__overlay_id__get_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                overlay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_overlay_create_overlay__overlay_id__get_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                overlay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_overlay_delete_overlay__overlay_id__delete_get_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                overlay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_overlay_delete_overlay__overlay_id__delete_get_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                overlay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_overlay_delete_overlay__overlay_id__delete_get_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                overlay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_overlays_list_overlay_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_manifest_manifest_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    serve_webmanifest_manifest_webmanifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    match_report_match__match_id__report_get: {
        parameters: {
            query?: {
                /** @description OVERLAY_MANAGER_PASSWORD; alternative to Bearer header. */
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
                "accept-language"?: string | null;
            };
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matches_index_matches_index_html_get: {
        parameters: {
            query: {
                /** @description Overlay ID to list matches for. */
                oid: string;
                /** @description OVERLAY_MANAGER_PASSWORD; alternative to Bearer header. */
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_archived_match_matches__match_id__delete: {
        parameters: {
            query?: {
                /** @description OVERLAY_MANAGER_PASSWORD; alternative to Bearer header. */
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_overlay_overlay__overlay_id__get: {
        parameters: {
            query?: {
                style?: string;
            };
            header?: never;
            path: {
                overlay_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_sw_sw_js_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
