"""Translation strings for the match-report and matches-index HTML pages.

The frontend has its own i18n system (``frontend/src/i18n.tsx``); this
module is the matching backend slice for server-rendered pages, where
the same locale keys aren't easily reachable. Locale resolution uses
the request's ``Accept-Language`` header, falling back to English.

Adding a string: add the key to ``_TRANSLATIONS["en"]`` first (the
fallback locale) and translate in the other locales. Missing keys
fall through to the English string at runtime, so partial coverage
in a non-English locale never breaks the page.
"""

from __future__ import annotations

import re
from typing import Optional

# Locales the report explicitly supports — kept in sync with the
# frontend selector. Any other ``Accept-Language`` value falls back
# to English.
SUPPORTED_LOCALES: tuple[str, ...] = ("en", "es", "pt", "it", "fr", "de")
DEFAULT_LOCALE = "en"


_TRANSLATIONS: dict[str, dict[str, str]] = {
    "en": {
        "title": "Match report — {label}",
        "duration": "Duration",
        "matchWinner": "Match winner",
        "setByset": "Set-by-set",
        "team": "Team",
        "timeoutsLabel": "Timeouts (final set)",
        "setDurations": "Set durations",
        "matchFacts": "Match facts",
        "matchId": "Match ID",
        "format": "Format",
        "formatDesc": "Best of {sets} · {points} pts/set ({last} in final)",
        "started": "Started",
        "ended": "Ended",
        "auditEntries": "Audit entries",
        "timeline": "Action timeline",
        "timelineHint": "Timestamps are relative to the match start.",
        "noAudit": "No audit records.",
        "footer": "Generated by Volley Overlay Control. Use your browser’s “Save as PDF” to export.",
        "actionPoint": "Point — Team {team}",
        "actionSet": "Set won — Team {team}",
        "actionTimeout": "Timeout — Team {team}",
        "actionServe": "Serve change → Team {team}",
        "actionScore": "Manual score — Team {team} set {set} = {value}",
        "actionReset": "Reset",
        "actionUnknown": "(unknown action)",
        "undo": " (undone)",
        "versus": "vs",
        "print": "Print",
        "printIncludeLogPrompt": "Include the action timeline in the printout?",
        "copyLink": "Copy link",
        "copyLinkOk": "Copied!",
        "highlights": "Highlights",
        "highlightStreak": "Longest scoring streak",
        "highlightComeback": "Biggest comeback",
        "highlightLongestRally": "Longest rally",
        "highlightTotalPoints": "Total points",
        "highlightLongestSet": "Longest set",
        "highlightShortestSet": "Shortest set",
        "pointsValue": "{n} pts",
        "deltaValue": "down {n}, won {set}",
        "scoreEvolution": "Score evolution",
        "setLabel": "Set {n}",
        "groupedSetLabel": "Set {n}",
        "noScoreEvolution": "Not enough scoring data to chart this set.",
    },
    "es": {
        "title": "Informe del partido — {label}",
        "duration": "Duración",
        "matchWinner": "Ganador del partido",
        "setByset": "Set a set",
        "team": "Equipo",
        "timeoutsLabel": "Tiempos muertos (set final)",
        "setDurations": "Duración de los sets",
        "matchFacts": "Datos del partido",
        "matchId": "ID del partido",
        "format": "Formato",
        "formatDesc": "Al mejor de {sets} · {points} pts/set ({last} en el final)",
        "started": "Inicio",
        "ended": "Fin",
        "auditEntries": "Entradas de auditoría",
        "timeline": "Cronología de acciones",
        "timelineHint": "Las marcas de tiempo son relativas al inicio del partido.",
        "noAudit": "Sin registros de auditoría.",
        "footer": "Generado por Volley Overlay Control. Usa la opción “Guardar como PDF” del navegador.",
        "actionPoint": "Punto — Equipo {team}",
        "actionSet": "Set ganado — Equipo {team}",
        "actionTimeout": "Tiempo muerto — Equipo {team}",
        "actionServe": "Cambio de saque → Equipo {team}",
        "actionScore": "Marcador manual — Equipo {team} set {set} = {value}",
        "actionReset": "Reinicio",
        "actionUnknown": "(acción desconocida)",
        "undo": " (deshecho)",
        "versus": "vs",
        "print": "Imprimir",
        "printIncludeLogPrompt": "¿Incluir la cronología de acciones en la impresión?",
        "copyLink": "Copiar enlace",
        "copyLinkOk": "¡Copiado!",
        "highlights": "Destacados",
        "highlightStreak": "Mayor racha anotadora",
        "highlightComeback": "Mayor remontada",
        "highlightLongestRally": "Punto más largo",
        "highlightTotalPoints": "Puntos totales",
        "highlightLongestSet": "Set más largo",
        "highlightShortestSet": "Set más corto",
        "pointsValue": "{n} pts",
        "deltaValue": "iba perdiendo por {n}, ganó el {set}",
        "scoreEvolution": "Evolución del marcador",
        "setLabel": "Set {n}",
        "groupedSetLabel": "Set {n}",
        "noScoreEvolution": "No hay datos suficientes para graficar este set.",
    },
    "pt": {
        "title": "Relatório do jogo — {label}",
        "duration": "Duração",
        "matchWinner": "Vencedor do jogo",
        "setByset": "Set a set",
        "team": "Equipa",
        "timeoutsLabel": "Tempos mortos (set final)",
        "setDurations": "Duração dos sets",
        "matchFacts": "Dados do jogo",
        "matchId": "ID do jogo",
        "format": "Formato",
        "formatDesc": "Melhor de {sets} · {points} pts/set ({last} no final)",
        "started": "Início",
        "ended": "Fim",
        "auditEntries": "Entradas de auditoria",
        "timeline": "Cronologia de ações",
        "timelineHint": "Os tempos são relativos ao início do jogo.",
        "noAudit": "Sem registos de auditoria.",
        "footer": "Gerado por Volley Overlay Control. Use “Guardar como PDF” do navegador.",
        "actionPoint": "Ponto — Equipa {team}",
        "actionSet": "Set ganho — Equipa {team}",
        "actionTimeout": "Tempo morto — Equipa {team}",
        "actionServe": "Troca de saque → Equipa {team}",
        "actionScore": "Pontuação manual — Equipa {team} set {set} = {value}",
        "actionReset": "Reinício",
        "actionUnknown": "(ação desconhecida)",
        "undo": " (desfeito)",
        "versus": "vs",
        "print": "Imprimir",
        "printIncludeLogPrompt": "Incluir a cronologia de ações na impressão?",
        "copyLink": "Copiar link",
        "copyLinkOk": "Copiado!",
        "highlights": "Destaques",
        "highlightStreak": "Maior sequência anotadora",
        "highlightComeback": "Maior virada",
        "highlightLongestRally": "Ponto mais longo",
        "highlightTotalPoints": "Pontos totais",
        "highlightLongestSet": "Set mais longo",
        "highlightShortestSet": "Set mais curto",
        "pointsValue": "{n} pts",
        "deltaValue": "atrás por {n}, venceu o {set}",
        "scoreEvolution": "Evolução do marcador",
        "setLabel": "Set {n}",
        "groupedSetLabel": "Set {n}",
        "noScoreEvolution": "Não há dados suficientes para o gráfico deste set.",
    },
    "it": {
        "title": "Referto della partita — {label}",
        "duration": "Durata",
        "matchWinner": "Vincitore della partita",
        "setByset": "Set per set",
        "team": "Squadra",
        "timeoutsLabel": "Time-out (set finale)",
        "setDurations": "Durata dei set",
        "matchFacts": "Dati della partita",
        "matchId": "ID partita",
        "format": "Formato",
        "formatDesc": "Al meglio di {sets} · {points} pti/set ({last} nel set finale)",
        "started": "Inizio",
        "ended": "Fine",
        "auditEntries": "Voci di audit",
        "timeline": "Cronologia delle azioni",
        "timelineHint": "I tempi sono relativi all’inizio della partita.",
        "noAudit": "Nessuna voce di audit.",
        "footer": "Generato da Volley Overlay Control. Usa “Salva come PDF” del browser.",
        "actionPoint": "Punto — Squadra {team}",
        "actionSet": "Set vinto — Squadra {team}",
        "actionTimeout": "Time-out — Squadra {team}",
        "actionServe": "Cambio battuta → Squadra {team}",
        "actionScore": "Punteggio manuale — Squadra {team} set {set} = {value}",
        "actionReset": "Reset",
        "actionUnknown": "(azione sconosciuta)",
        "undo": " (annullato)",
        "versus": "vs",
        "print": "Stampa",
        "printIncludeLogPrompt": "Includere la cronologia delle azioni nella stampa?",
        "copyLink": "Copia link",
        "copyLinkOk": "Copiato!",
        "highlights": "In evidenza",
        "highlightStreak": "Striscia di punti più lunga",
        "highlightComeback": "Rimonta più grande",
        "highlightLongestRally": "Scambio più lungo",
        "highlightTotalPoints": "Punti totali",
        "highlightLongestSet": "Set più lungo",
        "highlightShortestSet": "Set più corto",
        "pointsValue": "{n} pti",
        "deltaValue": "sotto di {n}, ha vinto il {set}",
        "scoreEvolution": "Evoluzione del punteggio",
        "setLabel": "Set {n}",
        "groupedSetLabel": "Set {n}",
        "noScoreEvolution": "Dati insufficienti per il grafico di questo set.",
    },
    "fr": {
        "title": "Rapport du match — {label}",
        "duration": "Durée",
        "matchWinner": "Vainqueur du match",
        "setByset": "Set par set",
        "team": "Équipe",
        "timeoutsLabel": "Temps morts (set décisif)",
        "setDurations": "Durée des sets",
        "matchFacts": "Données du match",
        "matchId": "ID du match",
        "format": "Format",
        "formatDesc": "Au meilleur de {sets} · {points} pts/set ({last} au final)",
        "started": "Début",
        "ended": "Fin",
        "auditEntries": "Entrées d’audit",
        "timeline": "Chronologie des actions",
        "timelineHint": "Les horodatages sont relatifs au début du match.",
        "noAudit": "Aucune entrée d’audit.",
        "footer": "Généré par Volley Overlay Control. Utilisez “Enregistrer en PDF” du navigateur.",
        "actionPoint": "Point — Équipe {team}",
        "actionSet": "Set gagné — Équipe {team}",
        "actionTimeout": "Temps mort — Équipe {team}",
        "actionServe": "Changement de service → Équipe {team}",
        "actionScore": "Score manuel — Équipe {team} set {set} = {value}",
        "actionReset": "Réinitialisation",
        "actionUnknown": "(action inconnue)",
        "undo": " (annulé)",
        "versus": "vs",
        "print": "Imprimer",
        "printIncludeLogPrompt": "Inclure la chronologie des actions dans l’impression ?",
        "copyLink": "Copier le lien",
        "copyLinkOk": "Copié !",
        "highlights": "Faits marquants",
        "highlightStreak": "Plus longue série marquée",
        "highlightComeback": "Plus gros retour",
        "highlightLongestRally": "Point le plus long",
        "highlightTotalPoints": "Points totaux",
        "highlightLongestSet": "Set le plus long",
        "highlightShortestSet": "Set le plus court",
        "pointsValue": "{n} pts",
        "deltaValue": "mené de {n}, gagné le {set}",
        "scoreEvolution": "Évolution du score",
        "setLabel": "Set {n}",
        "groupedSetLabel": "Set {n}",
        "noScoreEvolution": "Données insuffisantes pour ce set.",
    },
    "de": {
        "title": "Spielbericht — {label}",
        "duration": "Dauer",
        "matchWinner": "Spielsieger",
        "setByset": "Satz für Satz",
        "team": "Team",
        "timeoutsLabel": "Auszeiten (entscheidender Satz)",
        "setDurations": "Satzdauer",
        "matchFacts": "Spieldaten",
        "matchId": "Spiel-ID",
        "format": "Modus",
        "formatDesc": "Best of {sets} · {points} P./Satz ({last} im Entscheidungssatz)",
        "started": "Beginn",
        "ended": "Ende",
        "auditEntries": "Audit-Einträge",
        "timeline": "Aktionszeitleiste",
        "timelineHint": "Zeitangaben relativ zum Spielbeginn.",
        "noAudit": "Keine Audit-Einträge.",
        "footer": "Erstellt von Volley Overlay Control. Über “Als PDF speichern” des Browsers exportieren.",
        "actionPoint": "Punkt — Team {team}",
        "actionSet": "Satzgewinn — Team {team}",
        "actionTimeout": "Auszeit — Team {team}",
        "actionServe": "Aufschlagwechsel → Team {team}",
        "actionScore": "Manuelle Punktzahl — Team {team} Satz {set} = {value}",
        "actionReset": "Reset",
        "actionUnknown": "(unbekannte Aktion)",
        "undo": " (rückgängig)",
        "versus": "vs",
        "print": "Drucken",
        "printIncludeLogPrompt": "Aktionszeitleiste in den Ausdruck aufnehmen?",
        "copyLink": "Link kopieren",
        "copyLinkOk": "Kopiert!",
        "highlights": "Highlights",
        "highlightStreak": "Längste Punkteserie",
        "highlightComeback": "Größte Aufholjagd",
        "highlightLongestRally": "Längster Ballwechsel",
        "highlightTotalPoints": "Gesamtpunkte",
        "highlightLongestSet": "Längster Satz",
        "highlightShortestSet": "Kürzester Satz",
        "pointsValue": "{n} Pkt.",
        "deltaValue": "lag mit {n} zurück, gewann Satz {set}",
        "scoreEvolution": "Punkteverlauf",
        "setLabel": "Satz {n}",
        "groupedSetLabel": "Satz {n}",
        "noScoreEvolution": "Zu wenig Datenpunkte für diesen Satz.",
    },
}


_LANG_TAG_RE = re.compile(r"^[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*$")


def resolve_locale(accept_language: Optional[str]) -> str:
    """Pick the best supported locale for an ``Accept-Language`` header.

    Splits on ``,``, parses ``q=`` weights, and matches against
    :data:`SUPPORTED_LOCALES` by primary language tag (``es-ES`` → ``es``).
    Anything malformed or unrecognised falls back to English.
    """
    if not accept_language:
        return DEFAULT_LOCALE
    candidates: list[tuple[float, int, str]] = []
    for index, raw in enumerate(accept_language.split(",")):
        token = raw.strip()
        if not token:
            continue
        if ";" in token:
            tag, *params = (p.strip() for p in token.split(";"))
        else:
            tag, params = token, ()
        if not _LANG_TAG_RE.match(tag):
            continue
        q = 1.0
        for param in params:
            if param.startswith("q="):
                try:
                    q = float(param[2:])
                except ValueError:
                    q = 0.0
        primary = tag.split("-", 1)[0].lower()
        if primary in SUPPORTED_LOCALES:
            # Higher q first; preserve declaration order on ties so that
            # ``es,en`` picks ``es`` not ``en`` when both have q=1.
            candidates.append((-q, index, primary))
    if not candidates:
        return DEFAULT_LOCALE
    candidates.sort()
    return candidates[0][2]


def t(locale: str, key: str, **kwargs: object) -> str:
    """Look up ``key`` in *locale*, fall back to English, then to the key.

    ``**kwargs`` are interpolated via ``str.format`` so callers can write
    ``t(locale, "actionPoint", team=1)`` and get ``"Point — Team 1"``.
    Format errors collapse to the raw template string rather than raising,
    so a typo in a translation never 500s the report.
    """
    template = (
        _TRANSLATIONS.get(locale, _TRANSLATIONS[DEFAULT_LOCALE]).get(key)
        or _TRANSLATIONS[DEFAULT_LOCALE].get(key)
        or key
    )
    if not kwargs:
        return template
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError, ValueError):
        return template
