"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-27 00:36:48.222486
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_sessions_token_hash'))
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('match_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('oid', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('ended_at', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('winning_team', sa.Integer(), nullable=True),
    sa.Column('final_state', sa.JSON(), nullable=False),
    sa.Column('customization', sa.JSON(), nullable=False),
    sa.Column('audit_log', sa.JSON(), nullable=False),
    sa.Column('points_limit', sa.Integer(), nullable=True),
    sa.Column('points_limit_last_set', sa.Integer(), nullable=True),
    sa.Column('sets_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_match_reports_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_reports')),
    sa.UniqueConstraint('match_id', name=op.f('uq_match_reports_match_id'))
    )
    with op.batch_alter_table('match_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_reports_oid'), ['oid'], unique=False)
        batch_op.create_index('ix_match_reports_user_oid_ended', ['user_id', 'oid', 'ended_at'], unique=False)

    op.create_table('presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('scope_key', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_presets_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_presets')),
    sa.UniqueConstraint('scope_key', 'slug', name='uq_presets_scope_key_slug')
    )
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presets_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('team_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_team_groups_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_team_groups_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_groups'))
    )
    with op.batch_alter_table('team_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_groups_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('icon_url', sa.String(length=2048), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('text_color', sa.String(length=32), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_teams_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('user_overlays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('oid', sa.String(length=64), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=False),
    sa.Column('control_token', sa.String(length=64), nullable=True),
    sa.Column('public_control', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_overlays_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_overlays')),
    sa.UniqueConstraint('public_token', name=op.f('uq_user_overlays_public_token')),
    sa.UniqueConstraint('user_id', 'oid', name='uq_user_overlays_user_id_oid')
    )
    with op.batch_alter_table('user_overlays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_overlays_control_token'), ['control_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_overlays_user_id'), ['user_id'], unique=False)

    op.create_table('overlay_session_meta',
    sa.Column('overlay_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['overlay_id'], ['user_overlays.id'], name=op.f('fk_overlay_session_meta_overlay_id_user_overlays'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('overlay_id', name=op.f('pk_overlay_session_meta'))
    )
    op.create_table('team_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['team_groups.id'], name=op.f('fk_team_group_members_group_id_team_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_group_members_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_group_members')),
    sa.UniqueConstraint('group_id', 'team_id', name='uq_team_group_members_group_id_team_id')
    )
    with op.batch_alter_table('team_group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_group_members_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_group_members_team_id'), ['team_id'], unique=False)

    op.create_table('user_group_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['team_groups.id'], name=op.f('fk_user_group_teams_group_id_team_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_user_group_teams_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_group_teams_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_group_teams')),
    sa.UniqueConstraint('user_id', 'group_id', 'team_id', name='uq_user_group_teams_user_id_group_id_team_id')
    )
    with op.batch_alter_table('user_group_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_group_teams_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_group_teams_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_group_teams_user_id'), ['user_id'], unique=False)

    op.create_table('user_team_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_user_team_list_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_team_list_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_team_list')),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_user_team_list_user_id_team_id')
    )
    with op.batch_alter_table('user_team_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_team_list_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_team_list_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_team_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_team_list_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_team_list_team_id'))

    op.drop_table('user_team_list')
    with op.batch_alter_table('user_group_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_group_teams_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_group_teams_team_id'))
        batch_op.drop_index(batch_op.f('ix_user_group_teams_group_id'))

    op.drop_table('user_group_teams')
    with op.batch_alter_table('team_group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_group_members_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_group_members_group_id'))

    op.drop_table('team_group_members')
    op.drop_table('overlay_session_meta')
    with op.batch_alter_table('user_overlays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_overlays_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_overlays_control_token'))

    op.drop_table('user_overlays')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_owner_user_id'))

    op.drop_table('teams')
    with op.batch_alter_table('team_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_groups_owner_user_id'))

    op.drop_table('team_groups')
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presets_owner_user_id'))

    op.drop_table('presets')
    with op.batch_alter_table('match_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_match_reports_user_oid_ended')
        batch_op.drop_index(batch_op.f('ix_match_reports_oid'))

    op.drop_table('match_reports')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))

    op.drop_table('auth_sessions')
    op.drop_table('users')
    op.drop_table('settings')
    # ### end Alembic commands ###
