"""overlay output url + default match rules

Revision ID: 0002_overlay_settings
Revises: 0001_initial
Create Date: 2026-06-19 21:49:52.651452
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_overlay_settings'
down_revision: str | None = '0001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_overlays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_url', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('points_last_set', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sets', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_overlays', schema=None) as batch_op:
        batch_op.drop_column('sets')
        batch_op.drop_column('points_last_set')
        batch_op.drop_column('points')
        batch_op.drop_column('output_url')

    # ### end Alembic commands ###
