"""indexes on the columns every listing filters and orders by

Each index below backs a query that runs on a hot path and previously had
to scan its table (see #433):

* ``teams.is_global``   — the catalog listing, the "All" group, and the
  defence-in-depth filter on every group membership join.
* ``teams.name``        — the upsert key for the admin catalog import and
  the ``ORDER BY`` of four listings.
* ``team_groups.is_active`` — published-group listings.
* ``icons.is_global``   — the global icon library (deliberately uncapped).
* ``presets.scope`` + ``presets.is_active`` — the two halves of the
  ``list_for_user`` OR.
* ``auth_sessions.expires_at`` — the periodic expired-session sweeper
  added alongside this revision; without it the hourly purge would be a
  full-table scan.

All are plain (non-concurrent) ``CREATE INDEX`` statements: migrations run
inside the startup transaction, where Postgres forbids
``CREATE INDEX CONCURRENTLY``. These tables are small enough for the brief
write lock; an operator with an unusually large ``teams`` table can create
them by hand first, at which point this revision is a no-op stamp.

Revision ID: 0004_perf_indexes
Revises: 0003_drop_overlay_session_meta
Create Date: 2026-07-28 14:19:22.059434
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0004_perf_indexes'
down_revision: str | None = '0003_drop_overlay_session_meta'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_expires_at'), ['expires_at'], unique=False)

    with op.batch_alter_table('icons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_icons_is_global'), ['is_global'], unique=False)

    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presets_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_presets_scope'), ['scope'], unique=False)

    with op.batch_alter_table('team_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_groups_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_is_global'), ['is_global'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_name'))
        batch_op.drop_index(batch_op.f('ix_teams_is_global'))

    with op.batch_alter_table('team_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_groups_is_active'))

    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presets_scope'))
        batch_op.drop_index(batch_op.f('ix_presets_is_active'))

    with op.batch_alter_table('icons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_icons_is_global'))

    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_expires_at'))

    # ### end Alembic commands ###
