/*
 * Spectator (follow) page — read-only WebSocket consumer for
 * /follow/{output_key}. Subscribes to the same broadcast OBS uses
 * and renders into a mobile-first layout. Vanilla JS, no deps.
 */

(function () {
    'use strict';

    // ── i18n ────────────────────────────────────────────────────────
    //
    // We pick the language from the ``?lang=`` query string when present
    // (so a share link generated by the operator can preserve their UI
    // locale), then fall back to ``navigator.language``, then English.
    // The translation tables mirror the keys used in the template /
    // JS and the React-side ``i18n.tsx``.
    const TRANSLATIONS = {
        en: {
            'status.connecting': 'connecting…',
            'status.online': 'live',
            'status.offline': 'reconnecting…',
            'status.error': 'connection error',
            'board.sets': 'Sets',
            'board.setLabel': 'Set {set}',
            'chart.title': 'Set progression',
            'chart.empty': 'Waiting for the first point of the set…',
            'chart.nav.set': 'Set {set}',
            'chart.nav.setLive': 'Set {set} · live',
            'history.team': 'Team',
            'stats.streak.label': 'Streak',
            'stats.streak.value': '{name} · {n} in a row',
            'stats.totals': 'Total points',
            'stats.comeback.label': 'Comeback',
            'stats.comeback.value': '{name} · -{n}',
            'footer.label': 'Live updates',
        },
        es: {
            'status.connecting': 'conectando…',
            'status.online': 'en directo',
            'status.offline': 'reconectando…',
            'status.error': 'error de conexión',
            'board.sets': 'Sets',
            'board.setLabel': 'Set {set}',
            'chart.title': 'Evolución del set',
            'chart.empty': 'Esperando el primer punto del set…',
            'chart.nav.set': 'Set {set}',
            'chart.nav.setLive': 'Set {set} · en juego',
            'history.team': 'Equipo',
            'stats.streak.label': 'Racha',
            'stats.streak.value': '{name} · {n} seguidos',
            'stats.totals': 'Puntos totales',
            'stats.comeback.label': 'Remontada',
            'stats.comeback.value': '{name} · -{n}',
            'footer.label': 'Actualización en vivo',
        },
        pt: {
            'status.connecting': 'a ligar…',
            'status.online': 'em direto',
            'status.offline': 'a religar…',
            'status.error': 'erro de ligação',
            'board.sets': 'Sets',
            'board.setLabel': 'Set {set}',
            'chart.title': 'Evolução do set',
            'chart.empty': 'À espera do primeiro ponto do set…',
            'chart.nav.set': 'Set {set}',
            'chart.nav.setLive': 'Set {set} · ao vivo',
            'history.team': 'Equipa',
            'stats.streak.label': 'Sequência',
            'stats.streak.value': '{name} · {n} seguidos',
            'stats.totals': 'Pontos totais',
            'stats.comeback.label': 'Recuperação',
            'stats.comeback.value': '{name} · -{n}',
            'footer.label': 'Atualizações ao vivo',
        },
        it: {
            'status.connecting': 'connessione…',
            'status.online': 'in diretta',
            'status.offline': 'riconnessione…',
            'status.error': 'errore di connessione',
            'board.sets': 'Set',
            'board.setLabel': 'Set {set}',
            'chart.title': 'Andamento del set',
            'chart.empty': 'In attesa del primo punto del set…',
            'chart.nav.set': 'Set {set}',
            'chart.nav.setLive': 'Set {set} · in corso',
            'history.team': 'Squadra',
            'stats.streak.label': 'Serie',
            'stats.streak.value': '{name} · {n} di fila',
            'stats.totals': 'Punti totali',
            'stats.comeback.label': 'Rimonta',
            'stats.comeback.value': '{name} · -{n}',
            'footer.label': 'Aggiornamenti in diretta',
        },
        fr: {
            'status.connecting': 'connexion…',
            'status.online': 'en direct',
            'status.offline': 'reconnexion…',
            'status.error': 'erreur de connexion',
            'board.sets': 'Sets',
            'board.setLabel': 'Set {set}',
            'chart.title': 'Progression du set',
            'chart.empty': 'En attente du premier point du set…',
            'chart.nav.set': 'Set {set}',
            'chart.nav.setLive': 'Set {set} · en jeu',
            'history.team': 'Équipe',
            'stats.streak.label': 'Série',
            'stats.streak.value': '{name} · {n} d’affilée',
            'stats.totals': 'Points totaux',
            'stats.comeback.label': 'Remontée',
            'stats.comeback.value': '{name} · -{n}',
            'footer.label': 'Mises à jour en direct',
        },
        de: {
            'status.connecting': 'verbinde…',
            'status.online': 'live',
            'status.offline': 'verbinde neu…',
            'status.error': 'Verbindungsfehler',
            'board.sets': 'Sätze',
            'board.setLabel': 'Satz {set}',
            'chart.title': 'Satzverlauf',
            'chart.empty': 'Warte auf den ersten Punkt des Satzes…',
            'chart.nav.set': 'Satz {set}',
            'chart.nav.setLive': 'Satz {set} · live',
            'history.team': 'Team',
            'stats.streak.label': 'Serie',
            'stats.streak.value': '{name} · {n} in Folge',
            'stats.totals': 'Punkte gesamt',
            'stats.comeback.label': 'Aufholjagd',
            'stats.comeback.value': '{name} · -{n}',
            'footer.label': 'Live-Updates',
        },
    };

    function pickLanguage() {
        const qs = new URLSearchParams(window.location.search);
        const param = (qs.get('lang') || '').toLowerCase();
        if (param && TRANSLATIONS[param]) return param;
        const nav = (navigator.language || 'en').toLowerCase().split('-')[0];
        return TRANSLATIONS[nav] ? nav : 'en';
    }

    const LANG = pickLanguage();
    document.documentElement.setAttribute('lang', LANG);

    function t(key, args) {
        const bundle = TRANSLATIONS[LANG] || TRANSLATIONS.en;
        let str = bundle[key] || TRANSLATIONS.en[key] || key;
        if (args) {
            for (const k in args) {
                str = str.replace(new RegExp('\\{' + k + '\\}', 'g'), args[k]);
            }
        }
        return str;
    }

    // Apply static ``data-i18n`` / ``data-i18n-tpl`` translations on
    // first paint. Dynamic strings call ``t()`` directly inside their
    // render function.
    function applyStaticTranslations() {
        document.querySelectorAll('[data-i18n]').forEach((el) => {
            const key = el.getAttribute('data-i18n');
            el.textContent = t(key);
        });
        document.querySelectorAll('[data-i18n-tpl]').forEach((el) => {
            const key = el.getAttribute('data-i18n-tpl');
            const args = {};
            for (const attr of el.attributes) {
                if (attr.name.startsWith('data-arg-')) {
                    args[attr.name.slice('data-arg-'.length)] = attr.value;
                }
            }
            el.textContent = t(key, args);
        });
    }

    // ── DOM helpers ────────────────────────────────────────────────

    const OUTPUT_KEY = window.OVERLAY_OUTPUT_KEY;
    if (!OUTPUT_KEY) return;

    const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    const wsUrl = `${protocol}//${window.location.host}/ws/${OUTPUT_KEY}`;
    const $ = (id) => document.getElementById(id);

    function setText(id, value) {
        const el = $(id);
        if (el && el.textContent !== String(value)) el.textContent = String(value);
    }
    function setLogo(id, url) {
        const el = $(id);
        if (!el) return;
        if (url && /^(https?:|data:image\/)/i.test(url)) {
            if (el.getAttribute('src') !== url) el.setAttribute('src', url);
        } else {
            el.removeAttribute('src');
        }
    }
    function setHidden(id, hidden) {
        const el = $(id);
        if (!el) return;
        if (!!hidden) el.setAttribute('hidden', 'hidden');
        else el.removeAttribute('hidden');
    }
    function setStatus(text, state) {
        const el = $('conn-status');
        if (!el) return;
        el.textContent = text;
        if (state) el.dataset.state = state;
        else delete el.dataset.state;
    }
    function setStatsRow(id, label, value) {
        const row = $(id);
        if (!row) return;
        row.dataset.empty = value ? 'false' : 'true';
        if (!value) { row.textContent = ''; return; }
        row.textContent = '';
        const labelEl = document.createElement('span');
        labelEl.className = 'label';
        labelEl.textContent = label;
        const valueEl = document.createElement('span');
        valueEl.className = 'value';
        valueEl.textContent = value;
        row.appendChild(labelEl);
        row.appendChild(valueEl);
    }

    // ── Local state ────────────────────────────────────────────────

    // ``viewMode``:
    //   * "live" — chart follows the current set being played.
    //   * "frozen" — operator clicked prev/next; chart stays on the
    //     chosen set until "live" is restored (clicking the live set
    //     in the header or hitting Next past the last set).
    const state = {
        viewMode: 'live',
        viewedSet: 1,
        lastBroadcast: null,
    };

    function effectiveSet() {
        const broadcast = state.lastBroadcast || {};
        const currentSet = (broadcast.match_info || {}).current_set || 1;
        if (state.viewMode === 'live') return currentSet;
        return state.viewedSet;
    }

    // ── Render: scoreboard ─────────────────────────────────────────

    function renderScoreboard(broadcast) {
        const home = broadcast.team_home || {};
        const away = broadcast.team_away || {};
        const match = broadcast.match_info || {};

        const homeColor = home.color_primary || '#E21836';
        const awayColor = away.color_primary || '#0047AB';
        document.documentElement.style.setProperty('--team1-color', homeColor);
        document.documentElement.style.setProperty('--team2-color', awayColor);

        setText('team1-name', home.name || 'Team 1');
        setText('team2-name', away.name || 'Team 2');
        setText('team1-sets', home.sets_won || 0);
        setText('team2-sets', away.sets_won || 0);
        setText('team1-score', home.points || 0);
        setText('team2-score', away.points || 0);
        setLogo('team1-logo', home.logo_url);
        setLogo('team2-logo', away.logo_url);
        setHidden('team1-serve', !home.serving);
        setHidden('team2-serve', !away.serving);
        setText('set-label', t('board.setLabel', { set: match.current_set || 1 }));
        setText(
            'match-title',
            `${home.name || 'Team 1'} · ${away.name || 'Team 2'}`,
        );
        setText('legend-name-home', home.name || 'Team 1');
        setText('legend-name-away', away.name || 'Team 2');
        const swHome = $('legend-swatch-home');
        if (swHome) swHome.style.background = homeColor;
        const swAway = $('legend-swatch-away');
        if (swAway) swAway.style.background = awayColor;
    }

    // ── Render: set history table (clickable rows) ─────────────────

    function renderHistory(broadcast) {
        const home = broadcast.team_home || {};
        const away = broadcast.team_away || {};
        const match = broadcast.match_info || {};
        const best = Math.max(1, Math.min(7, match.best_of_sets || 5));
        const currentSet = match.current_set || 1;
        const viewed = effectiveSet();

        const headRow = $('history-head');
        const homeRow = $('history-row-home');
        const awayRow = $('history-row-away');
        if (!headRow || !homeRow || !awayRow) return;
        headRow.textContent = '';
        homeRow.textContent = '';
        awayRow.textContent = '';

        const teamHeader = document.createElement('th');
        teamHeader.textContent = t('history.team');
        headRow.appendChild(teamHeader);

        const homeLabel = document.createElement('td');
        homeLabel.className = 'team-cell';
        homeLabel.textContent = home.name || 'Team 1';
        homeRow.appendChild(homeLabel);

        const awayLabel = document.createElement('td');
        awayLabel.className = 'team-cell';
        awayLabel.textContent = away.name || 'Team 2';
        awayRow.appendChild(awayLabel);

        for (let i = 1; i <= best; i += 1) {
            const th = document.createElement('th');
            th.className = 'chart-cell';
            th.textContent = `S${i}`;
            if (i === viewed) th.classList.add('active-set');
            th.addEventListener('click', () => switchToSet(i, currentSet));
            headRow.appendChild(th);

            const homeCell = document.createElement('td');
            const awayCell = document.createElement('td');
            const homeScore = (home.set_history || {})[`set_${i}`] || 0;
            const awayScore = (away.set_history || {})[`set_${i}`] || 0;
            homeCell.textContent = homeScore;
            awayCell.textContent = awayScore;
            homeCell.className = 'chart-cell';
            awayCell.className = 'chart-cell';
            if (i === currentSet) {
                homeCell.classList.add('live-cell');
                awayCell.classList.add('live-cell');
            }
            if (i === viewed) {
                homeCell.classList.add('active-set');
                awayCell.classList.add('active-set');
            }
            homeCell.addEventListener('click', () => switchToSet(i, currentSet));
            awayCell.addEventListener('click', () => switchToSet(i, currentSet));
            homeRow.appendChild(homeCell);
            awayRow.appendChild(awayCell);
        }
    }

    // ── Render: live stats ─────────────────────────────────────────

    function renderStats(broadcast) {
        const oc = broadcast.overlay_control || {};
        const stats = oc.stats || {};
        const cs = stats.current_streak || {};
        const pc = stats.partial_comeback || {};
        const home = broadcast.team_home || {};
        const away = broadcast.team_away || {};

        if (cs.team && cs.n >= 2) {
            const name = cs.team === 1
                ? (home.name || 'Team 1')
                : (away.name || 'Team 2');
            setStatsRow(
                'stats-streak',
                t('stats.streak.label'),
                t('stats.streak.value', { name: name, n: cs.n }),
            );
        } else {
            setStatsRow('stats-streak', '', '');
        }

        if (typeof stats.total_points === 'number' && stats.total_points > 0) {
            setStatsRow('stats-totals', t('stats.totals'), String(stats.total_points));
        } else {
            setStatsRow('stats-totals', '', '');
        }

        const pcHome = pc[1] || pc['1'] || {};
        const pcAway = pc[2] || pc['2'] || {};
        const peak = Math.max(pcHome.deficit || 0, pcAway.deficit || 0);
        if (peak >= 3) {
            const team = (pcHome.deficit || 0) >= (pcAway.deficit || 0) ? 1 : 2;
            const name = team === 1
                ? (home.name || 'Team 1')
                : (away.name || 'Team 2');
            setStatsRow(
                'stats-comeback',
                t('stats.comeback.label'),
                t('stats.comeback.value', { name: name, n: peak }),
            );
        } else {
            setStatsRow('stats-comeback', '', '');
        }
    }

    // ── Render: set progression chart ──────────────────────────────

    function renderSetChart(broadcast) {
        const empty = $('set-chart-empty');
        const svg = $('set-chart-svg');
        const lineHome = $('set-chart-line-home');
        const lineAway = $('set-chart-line-away');
        const grid = $('set-chart-grid');
        const navLabel = $('set-nav-label');
        if (!svg || !lineHome || !lineAway || !empty || !grid || !navLabel) return;

        const oc = broadcast.overlay_control || {};
        const match = broadcast.match_info || {};
        const homeColor = (broadcast.team_home || {}).color_primary || '#E21836';
        const awayColor = (broadcast.team_away || {}).color_primary || '#0047AB';
        const currentSet = match.current_set || 1;
        const bySet = oc.points_by_set || {};
        const setNum = effectiveSet();

        // Update nav header.
        const isLive = setNum === currentSet;
        const labelKey = isLive ? 'chart.nav.setLive' : 'chart.nav.set';
        navLabel.textContent = t(labelKey, { set: setNum });

        // Disable prev/next when at boundaries.
        const best = Math.max(1, Math.min(7, match.best_of_sets || 5));
        const prevBtn = $('set-prev');
        const nextBtn = $('set-next');
        if (prevBtn) prevBtn.disabled = setNum <= 1;
        if (nextBtn) nextBtn.disabled = setNum >= best || (state.viewMode === 'live');

        const events = bySet[String(setNum)] || bySet[setNum] || [];

        if (!events.length) {
            svg.setAttribute('hidden', 'hidden');
            empty.removeAttribute('hidden');
            lineHome.setAttribute('d', '');
            lineAway.setAttribute('d', '');
            grid.textContent = '';
            return;
        }

        svg.removeAttribute('hidden');
        empty.setAttribute('hidden', 'hidden');

        // Project. ViewBox is 600x180 with padding so axis text fits.
        const W = 600;
        const H = 180;
        const PAD_L = 28;
        const PAD_R = 12;
        const PAD_T = 12;
        const PAD_B = 18;
        const innerW = W - PAD_L - PAD_R;
        const innerH = H - PAD_T - PAD_B;

        // Series: synthetic 0-0 baseline + one entry per event.
        const series = [[0, 0]];
        for (const p of events) {
            const s = Array.isArray(p.score) ? p.score : [0, 0];
            series.push([s[0] || 0, s[1] || 0]);
        }
        const maxIdx = Math.max(1, series.length - 1);
        const maxScore = Math.max(
            1,
            ...series.map((pair) => Math.max(pair[0], pair[1])),
        );

        function project(idx, score) {
            const x = PAD_L + (idx / maxIdx) * innerW;
            const y = PAD_T + innerH - (score / maxScore) * innerH;
            return [x, y];
        }

        function buildPath(teamIdx) {
            return series
                .map((pair, i) => {
                    const [x, y] = project(i, pair[teamIdx]);
                    return `${i === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`;
                })
                .join(' ');
        }

        lineHome.setAttribute('d', buildPath(0));
        lineAway.setAttribute('d', buildPath(1));
        // Inline ``stroke`` wins over the CSS rule and over
        // ``currentColor`` so the two lines are guaranteed to be
        // distinct even when the brand colours don't reach the SVG.
        lineHome.setAttribute('stroke', homeColor);
        lineAway.setAttribute('stroke', awayColor);

        // Y-axis: render up to 5 evenly-spaced ticks. ``maxScore`` can
        // be small early in a set; in that case we render one tick per
        // integer score so we don't get duplicate "0 / 0 / 0" labels.
        grid.textContent = '';
        const tickCount = Math.min(5, Math.max(2, maxScore + 1));
        const seen = new Set();
        for (let i = 0; i < tickCount; i += 1) {
            const value = Math.round((i / (tickCount - 1)) * maxScore);
            if (seen.has(value)) continue;
            seen.add(value);
            const [, y] = project(0, value);
            const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
            line.setAttribute('x1', String(PAD_L));
            line.setAttribute('x2', String(W - PAD_R));
            line.setAttribute('y1', y.toFixed(1));
            line.setAttribute('y2', y.toFixed(1));
            grid.appendChild(line);

            const text = document.createElementNS('http://www.w3.org/2000/svg', 'text');
            text.setAttribute('x', '6');
            text.setAttribute('y', (y + 4).toFixed(1));
            text.textContent = String(value);
            grid.appendChild(text);
        }
    }

    // ── Set navigation ─────────────────────────────────────────────

    function switchToSet(setNum, currentSet) {
        if (setNum < 1) return;
        if (setNum === currentSet) {
            state.viewMode = 'live';
        } else {
            state.viewMode = 'frozen';
            state.viewedSet = setNum;
        }
        renderAll();
    }

    function wireNavButtons() {
        const prev = $('set-prev');
        const next = $('set-next');
        if (prev) prev.addEventListener('click', () => {
            const broadcast = state.lastBroadcast || {};
            const currentSet = (broadcast.match_info || {}).current_set || 1;
            switchToSet(Math.max(1, effectiveSet() - 1), currentSet);
        });
        if (next) next.addEventListener('click', () => {
            const broadcast = state.lastBroadcast || {};
            const currentSet = (broadcast.match_info || {}).current_set || 1;
            const best = Math.max(
                1, Math.min(7, (broadcast.match_info || {}).best_of_sets || 5),
            );
            switchToSet(Math.min(best, effectiveSet() + 1), currentSet);
        });
    }

    // ── Top-level render ───────────────────────────────────────────

    function renderAll() {
        const broadcast = state.lastBroadcast;
        if (!broadcast) return;
        renderScoreboard(broadcast);
        renderHistory(broadcast);
        renderStats(broadcast);
        renderSetChart(broadcast);
    }

    function render(broadcast) {
        if (!broadcast || typeof broadcast !== 'object') return;
        state.lastBroadcast = broadcast;
        // While in "live" mode the viewed set tracks the current set.
        if (state.viewMode === 'live') {
            state.viewedSet = (broadcast.match_info || {}).current_set || 1;
        }
        renderAll();
    }

    // ── WebSocket lifecycle ────────────────────────────────────────

    let ws = null;
    let reconnectAttempts = 0;
    let reconnectTimer = null;

    function connect() {
        try {
            ws = new WebSocket(wsUrl);
        } catch (err) {
            setStatus(t('status.error'), 'offline');
            scheduleReconnect();
            return;
        }
        setStatus(t('status.connecting'));

        ws.addEventListener('open', () => {
            setStatus(t('status.online'), 'online');
            reconnectAttempts = 0;
        });
        ws.addEventListener('message', (event) => {
            try {
                render(JSON.parse(event.data));
            } catch (_err) {
                /* ignore malformed frames */
            }
        });
        ws.addEventListener('close', () => {
            setStatus(t('status.offline'), 'offline');
            scheduleReconnect();
        });
        ws.addEventListener('error', () => {
            /* close handler will run; nothing extra to do here */
        });
    }

    function scheduleReconnect() {
        if (reconnectTimer) return;
        const delay = Math.min(15000, 1000 * Math.pow(2, reconnectAttempts));
        reconnectAttempts += 1;
        reconnectTimer = setTimeout(() => {
            reconnectTimer = null;
            connect();
        }, delay);
    }

    // ── Init ───────────────────────────────────────────────────────

    applyStaticTranslations();
    wireNavButtons();
    connect();
})();
