/*
 * Spectator (follow) page — read-only WebSocket consumer for
 * /follow/{output_key}. Subscribes to the same broadcast OBS uses
 * and renders into a mobile-first layout. Vanilla JS, no deps.
 */

(function () {
    'use strict';

    // ── i18n ────────────────────────────────────────────────────────
    //
    // We pick the language from the ``?lang=`` query string when present
    // (so a share link generated by the operator can preserve their UI
    // locale), then fall back to ``navigator.language``, then English.
    // The translation tables mirror the keys used in the template /
    // JS and the React-side ``i18n.tsx``.
    const TRANSLATIONS = {
        en: {
            'doc.title': 'Live scoreboard',
            'status.connecting': 'connecting…',
            'status.online': 'live',
            'status.offline': 'reconnecting…',
            'status.error': 'connection error',
            'board.sets': 'Sets',
            'board.timeouts': 'T/O',
            'board.setLabel': 'Set {set}',
            'board.setTime': 'Set',
            'board.matchTime': 'Match',
            'rules.mode.indoor': 'Indoor',
            'rules.mode.beach': 'Beach',
            'rules.bestOf': 'Best of {n}',
            'rules.points': '{regular} · {last} in deciding set',
            'rules.switchEvery': 'Side switch every {n} pts',
            'alert.setPoint': 'Set point',
            'alert.matchPoint': 'Match point',
            'alert.switchIn': 'Switch in {n} pt',
            'alert.switchInPlural': 'Switch in {n} pts',
            'alert.switchNow': 'Side switch now',
            'chart.title': 'Set progression',
            'chart.empty': 'Waiting for the first point of the set…',
            'chart.nav.set': 'Set {set}',
            'chart.nav.setLive': 'Set {set} · live',
            'chart.timeoutBadge': 'T',
            'history.team': 'Team',
            'stats.totals': 'Total points',
            'stats.services.label': 'Services won',
            'stats.services.cell': '{won}/{total}',
            'stats.streak.label': 'Streak',
            'stats.streak.cell': '{n}',
            'stats.longest.label': 'Longest streak',
            'stats.comeback.label': 'Comeback',
            'stats.comeback.cell': '-{n}',
            'footer.label': 'Live updates',
        },
        es: {
            'doc.title': 'Marcador en directo',
            'status.connecting': 'conectando…',
            'status.online': 'en directo',
            'status.offline': 'reconectando…',
            'status.error': 'error de conexión',
            'board.sets': 'Sets',
            'board.timeouts': 'T/M',
            'board.setLabel': 'Set {set}',
            'board.setTime': 'Set',
            'board.matchTime': 'Partido',
            'rules.mode.indoor': 'Indoor',
            'rules.mode.beach': 'Playa',
            'rules.bestOf': 'Al mejor de {n}',
            'rules.points': '{regular} · {last} en set decisivo',
            'rules.switchEvery': 'Cambio cada {n} pts',
            'alert.setPoint': 'Punto de set',
            'alert.matchPoint': 'Punto de partido',
            'alert.switchIn': 'Cambio en {n} pt',
            'alert.switchInPlural': 'Cambio en {n} pts',
            'alert.switchNow': 'Cambiar de campo',
            'chart.title': 'Evolución del set',
            'chart.empty': 'Esperando el primer punto del set…',
            'chart.nav.set': 'Set {set}',
            'chart.nav.setLive': 'Set {set} · en juego',
            'chart.timeoutBadge': 'TM',
            'history.team': 'Equipo',
            'stats.totals': 'Puntos totales',
            'stats.services.label': 'Saques ganados',
            'stats.services.cell': '{won}/{total}',
            'stats.streak.label': 'Racha',
            'stats.streak.cell': '{n}',
            'stats.longest.label': 'Racha más larga',
            'stats.comeback.label': 'Remontada',
            'stats.comeback.cell': '-{n}',
            'footer.label': 'Actualización en vivo',
        },
        pt: {
            'doc.title': 'Placar ao vivo',
            'status.connecting': 'a ligar…',
            'status.online': 'em direto',
            'status.offline': 'a religar…',
            'status.error': 'erro de ligação',
            'board.sets': 'Sets',
            'board.timeouts': 'T/M',
            'board.setLabel': 'Set {set}',
            'board.setTime': 'Set',
            'board.matchTime': 'Partida',
            'rules.mode.indoor': 'Indoor',
            'rules.mode.beach': 'Praia',
            'rules.bestOf': 'À melhor de {n}',
            'rules.points': '{regular} · {last} no set decisivo',
            'rules.switchEvery': 'Mudança cada {n} pts',
            'alert.setPoint': 'Ponto de set',
            'alert.matchPoint': 'Ponto de partida',
            'alert.switchIn': 'Mudança em {n} pt',
            'alert.switchInPlural': 'Mudança em {n} pts',
            'alert.switchNow': 'Mudar de campo',
            'chart.title': 'Evolução do set',
            'chart.empty': 'À espera do primeiro ponto do set…',
            'chart.nav.set': 'Set {set}',
            'chart.nav.setLive': 'Set {set} · ao vivo',
            'chart.timeoutBadge': 'TM',
            'history.team': 'Equipa',
            'stats.totals': 'Pontos totais',
            'stats.services.label': 'Serviços ganhos',
            'stats.services.cell': '{won}/{total}',
            'stats.streak.label': 'Sequência',
            'stats.streak.cell': '{n}',
            'stats.longest.label': 'Sequência mais longa',
            'stats.comeback.label': 'Recuperação',
            'stats.comeback.cell': '-{n}',
            'footer.label': 'Atualizações ao vivo',
        },
        it: {
            'doc.title': 'Tabellone in diretta',
            'status.connecting': 'connessione…',
            'status.online': 'in diretta',
            'status.offline': 'riconnessione…',
            'status.error': 'errore di connessione',
            'board.sets': 'Set',
            'board.timeouts': 'T/O',
            'board.setLabel': 'Set {set}',
            'board.setTime': 'Set',
            'board.matchTime': 'Partita',
            'rules.mode.indoor': 'Indoor',
            'rules.mode.beach': 'Beach',
            'rules.bestOf': 'Al meglio dei {n}',
            'rules.points': '{regular} · {last} nel set decisivo',
            'rules.switchEvery': 'Cambio campo ogni {n} pt',
            'alert.setPoint': 'Set point',
            'alert.matchPoint': 'Match point',
            'alert.switchIn': 'Cambio tra {n} pt',
            'alert.switchInPlural': 'Cambio tra {n} pt',
            'alert.switchNow': 'Cambiare campo',
            'chart.title': 'Andamento del set',
            'chart.empty': 'In attesa del primo punto del set…',
            'chart.nav.set': 'Set {set}',
            'chart.nav.setLive': 'Set {set} · in corso',
            'chart.timeoutBadge': 'TO',
            'history.team': 'Squadra',
            'stats.totals': 'Punti totali',
            'stats.services.label': 'Servizi vinti',
            'stats.services.cell': '{won}/{total}',
            'stats.streak.label': 'Serie',
            'stats.streak.cell': '{n}',
            'stats.longest.label': 'Serie più lunga',
            'stats.comeback.label': 'Rimonta',
            'stats.comeback.cell': '-{n}',
            'footer.label': 'Aggiornamenti in diretta',
        },
        fr: {
            'doc.title': 'Tableau en direct',
            'status.connecting': 'connexion…',
            'status.online': 'en direct',
            'status.offline': 'reconnexion…',
            'status.error': 'erreur de connexion',
            'board.sets': 'Sets',
            'board.timeouts': 'T/M',
            'board.setLabel': 'Set {set}',
            'board.setTime': 'Set',
            'board.matchTime': 'Match',
            'rules.mode.indoor': 'Salle',
            'rules.mode.beach': 'Plage',
            'rules.bestOf': 'Au meilleur des {n}',
            'rules.points': '{regular} · {last} dans le set décisif',
            'rules.switchEvery': 'Changement tous les {n} pts',
            'alert.setPoint': 'Balle de set',
            'alert.matchPoint': 'Balle de match',
            'alert.switchIn': 'Changement dans {n} pt',
            'alert.switchInPlural': 'Changement dans {n} pts',
            'alert.switchNow': 'Changer de côté',
            'chart.title': 'Progression du set',
            'chart.empty': 'En attente du premier point du set…',
            'chart.nav.set': 'Set {set}',
            'chart.nav.setLive': 'Set {set} · en jeu',
            'chart.timeoutBadge': 'TM',
            'history.team': 'Équipe',
            'stats.totals': 'Points totaux',
            'stats.services.label': 'Services gagnés',
            'stats.services.cell': '{won}/{total}',
            'stats.streak.label': 'Série',
            'stats.streak.cell': '{n}',
            'stats.longest.label': 'Plus longue série',
            'stats.comeback.label': 'Remontée',
            'stats.comeback.cell': '-{n}',
            'footer.label': 'Mises à jour en direct',
        },
        de: {
            'doc.title': 'Live-Anzeigetafel',
            'status.connecting': 'verbinde…',
            'status.online': 'live',
            'status.offline': 'verbinde neu…',
            'status.error': 'Verbindungsfehler',
            'board.sets': 'Sätze',
            'board.timeouts': 'A/Z',
            'board.setLabel': 'Satz {set}',
            'board.setTime': 'Satz',
            'board.matchTime': 'Spiel',
            'rules.mode.indoor': 'Halle',
            'rules.mode.beach': 'Beach',
            'rules.bestOf': 'Best of {n}',
            'rules.points': '{regular} · {last} im Entscheidungssatz',
            'rules.switchEvery': 'Seitenwechsel alle {n} Pkt',
            'alert.setPoint': 'Satzball',
            'alert.matchPoint': 'Matchball',
            'alert.switchIn': 'Wechsel in {n} Pkt',
            'alert.switchInPlural': 'Wechsel in {n} Pkt',
            'alert.switchNow': 'Jetzt Seiten wechseln',
            'chart.title': 'Satzverlauf',
            'chart.empty': 'Warte auf den ersten Punkt des Satzes…',
            'chart.nav.set': 'Satz {set}',
            'chart.nav.setLive': 'Satz {set} · live',
            'chart.timeoutBadge': 'AZ',
            'history.team': 'Team',
            'stats.totals': 'Punkte gesamt',
            'stats.services.label': 'Aufschläge gewonnen',
            'stats.services.cell': '{won}/{total}',
            'stats.streak.label': 'Serie',
            'stats.streak.cell': '{n}',
            'stats.longest.label': 'Längste Serie',
            'stats.comeback.label': 'Aufholjagd',
            'stats.comeback.cell': '-{n}',
            'footer.label': 'Live-Updates',
        },
    };

    function pickLanguage() {
        const qs = new URLSearchParams(window.location.search);
        const param = (qs.get('lang') || '').toLowerCase();
        if (param && TRANSLATIONS[param]) return param;
        const nav = (navigator.language || 'en').toLowerCase().split('-')[0];
        return TRANSLATIONS[nav] ? nav : 'en';
    }

    const LANG = pickLanguage();
    document.documentElement.setAttribute('lang', LANG);
    // Replace the server-rendered placeholder ``<title>`` with a
    // localised version. The Jinja template emits a neutral English
    // string so search engines / link previewers see something
    // reasonable before the JS runs.
    try {
        document.title = (TRANSLATIONS[LANG] || TRANSLATIONS.en)['doc.title']
            || document.title;
    } catch (_e) { /* ignore */ }

    function t(key, args) {
        const bundle = TRANSLATIONS[LANG] || TRANSLATIONS.en;
        let str = bundle[key] || TRANSLATIONS.en[key] || key;
        if (args) {
            for (const k in args) {
                str = str.replace(new RegExp('\\{' + k + '\\}', 'g'), args[k]);
            }
        }
        return str;
    }

    // Apply static ``data-i18n`` / ``data-i18n-tpl`` translations on
    // first paint. Dynamic strings call ``t()`` directly inside their
    // render function.
    function applyStaticTranslations() {
        document.querySelectorAll('[data-i18n]').forEach((el) => {
            const key = el.getAttribute('data-i18n');
            el.textContent = t(key);
        });
        document.querySelectorAll('[data-i18n-tpl]').forEach((el) => {
            const key = el.getAttribute('data-i18n-tpl');
            const args = {};
            for (const attr of el.attributes) {
                if (attr.name.startsWith('data-arg-')) {
                    args[attr.name.slice('data-arg-'.length)] = attr.value;
                }
            }
            el.textContent = t(key, args);
        });
    }

    // ── DOM helpers ────────────────────────────────────────────────

    const OUTPUT_KEY = window.OVERLAY_OUTPUT_KEY;
    if (!OUTPUT_KEY) return;

    const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    const wsUrl = `${protocol}//${window.location.host}/ws/${OUTPUT_KEY}`;
    const $ = (id) => document.getElementById(id);

    function setText(id, value) {
        const el = $(id);
        if (el && el.textContent !== String(value)) el.textContent = String(value);
    }
    function setLogo(id, url) {
        const el = $(id);
        if (!el) return;
        if (!url || typeof url !== 'string') {
            el.removeAttribute('src');
            return;
        }
        // Parse through the URL constructor so we have an authoritative
        // protocol check instead of a regex on the raw string. CodeQL
        // doesn't model regex-based sanitisation; using ``URL`` makes
        // the allow-list explicit and serialises the result back via
        // ``parsed.href`` so any odd characters get encoded.
        let parsed;
        try {
            parsed = new URL(url, window.location.href);
        } catch (_e) {
            el.removeAttribute('src');
            return;
        }
        const proto = parsed.protocol;
        const isHttp = proto === 'http:' || proto === 'https:';
        const isImageData = proto === 'data:' && parsed.pathname.toLowerCase().startsWith('image/');
        if (!isHttp && !isImageData) {
            el.removeAttribute('src');
            return;
        }
        const safe = parsed.href;
        if (el.getAttribute('src') !== safe) el.setAttribute('src', safe);
    }
    function setHidden(id, hidden) {
        const el = $(id);
        if (!el) return;
        if (!!hidden) el.setAttribute('hidden', 'hidden');
        else el.removeAttribute('hidden');
    }
    function setStatus(text, state) {
        const el = $('conn-status');
        if (!el) return;
        el.textContent = text;
        if (state) el.dataset.state = state;
        else delete el.dataset.state;
    }
    function setStatsRow(id, label, value) {
        const row = $(id);
        if (!row) return;
        row.dataset.empty = value ? 'false' : 'true';
        if (!value) { row.textContent = ''; return; }
        row.textContent = '';
        const labelEl = document.createElement('span');
        labelEl.className = 'label';
        labelEl.textContent = label;
        const valueEl = document.createElement('span');
        valueEl.className = 'value';
        valueEl.textContent = value;
        row.appendChild(labelEl);
        row.appendChild(valueEl);
    }

    // ── Chart-color collision handling ─────────────────────────────
    //
    // When both teams' brand colours land on essentially the same hue
    // the chart lines collapse to a single visible trace. We mirror the
    // print-side ``_ensure_distinct_chart_colors`` helper from
    // ``app/match_report.py``: if the two colours are within a small
    // RGB euclidean distance, swap the away team's chart colour for
    // the fallback that's farthest from the home colour, AND apply a
    // dashed stroke to the away line so even an extreme edge case
    // (two reds + a red fallback) still reads as two distinct lines.

    const COLOR_FALLBACK = ['#0047AB', '#E21836'];
    // Threshold tuned empirically on the brand palettes that ship in
    // the bundled themes: differences below ~60 RGB units (e.g. two
    // reds that only differ in saturation) read as the same colour
    // when drawn at 2.4px stroke width on a dark background.
    const COLOR_COLLISION_THRESHOLD = 60;

    function hexToRgb(hex) {
        if (typeof hex !== 'string') return null;
        const m = hex.replace(/^#/, '');
        if (!/^[0-9a-fA-F]+$/.test(m)) return null;
        if (m.length === 3) {
            return [
                parseInt(m[0] + m[0], 16),
                parseInt(m[1] + m[1], 16),
                parseInt(m[2] + m[2], 16),
            ];
        }
        if (m.length === 6) {
            return [
                parseInt(m.slice(0, 2), 16),
                parseInt(m.slice(2, 4), 16),
                parseInt(m.slice(4, 6), 16),
            ];
        }
        return null;
    }

    function colorDistance(a, b) {
        const ra = hexToRgb(a);
        const rb = hexToRgb(b);
        if (!ra || !rb) return Infinity;
        const dr = ra[0] - rb[0];
        const dg = ra[1] - rb[1];
        const db = ra[2] - rb[2];
        return Math.sqrt(dr * dr + dg * dg + db * db);
    }

    function resolveChartColors(homeColor, awayColor) {
        const dist = colorDistance(homeColor, awayColor);
        if (dist > COLOR_COLLISION_THRESHOLD) {
            return { home: homeColor, away: awayColor, collision: false };
        }
        // Pick the fallback whose distance to the home colour is largest
        // — guarantees the chosen swap is the most visually distinct
        // option in the small fallback palette.
        const fb = colorDistance(homeColor, COLOR_FALLBACK[0])
            >= colorDistance(homeColor, COLOR_FALLBACK[1])
            ? COLOR_FALLBACK[0]
            : COLOR_FALLBACK[1];
        return { home: homeColor, away: fb, collision: true };
    }

    // ── Local state ────────────────────────────────────────────────

    // ``viewMode``:
    //   * "live" — chart follows the current set being played.
    //   * "frozen" — operator clicked prev/next; chart stays on the
    //     chosen set until "live" is restored (clicking the live set
    //     in the header or hitting Next past the last set).
    const state = {
        viewMode: 'live',
        viewedSet: 1,
        lastBroadcast: null,
    };

    function effectiveSet() {
        const broadcast = state.lastBroadcast || {};
        const currentSet = (broadcast.match_info || {}).current_set || 1;
        if (state.viewMode === 'live') return currentSet;
        return state.viewedSet;
    }

    // ── Render: rules summary + alerts ─────────────────────────────

    function renderRulesSummary(broadcast) {
        const match = broadcast.match_info || {};
        const el = $('rules-summary');
        if (!el) return;
        const mode = match.mode === 'beach' ? 'beach' : 'indoor';
        const sets = match.best_of_sets;
        const reg = match.points_limit;
        const last = match.points_limit_last_set;
        if (!sets || !reg || !last) {
            el.setAttribute('hidden', 'hidden');
            el.textContent = '';
            return;
        }
        const parts = [
            t('rules.mode.' + mode),
            t('rules.bestOf', { n: sets }),
            t('rules.points', { regular: reg, last: last }),
        ];
        if (mode === 'beach') {
            // The side-switch interval is derived the same way the
            // backend does it: 5 if the current set target ≤ 15, else 7.
            // We compute locally so the badge updates immediately on
            // rule changes without waiting for the next score event.
            const currentSet = match.current_set || 1;
            const target = currentSet >= sets ? last : reg;
            const interval = target <= 15 ? 5 : 7;
            parts.push(t('rules.switchEvery', { n: interval }));
        }
        el.textContent = parts.join(' · ');
        el.removeAttribute('hidden');
    }

    /*
     * Set + match elapsed counters. The match clock ticks live from
     * ``match_info.match_started_at`` if present; the set clock is
     * derived from the viewed set's first / last scoring-event
     * timestamps (so a paused set freezes correctly) but rolls forward
     * for the *current* set whenever the set is live — there we add
     * "time since the last event" so the counter reads naturally
     * between rallies. Falls back to the audit-derived
     * ``set_durations`` map for past sets.
     */
    function renderTimers(broadcast) {
        const wrap = $('match-times');
        const setEl = $('set-time-value');
        const matchEl = $('match-time-value');
        if (!wrap || !setEl || !matchEl) return;

        const match = broadcast.match_info || {};
        const oc = broadcast.overlay_control || {};
        const stats = oc.stats || {};
        const setDurations = stats.set_durations || {};
        const setNum = effectiveSet();
        const currentSet = match.current_set || 1;
        const isLiveSet = setNum === currentSet;

        const bySet = oc.points_by_set || {};
        const setEvents = bySet[String(setNum)] || bySet[setNum] || [];
        const setStamps = setEvents
            .map((e) => (typeof e.ts === 'number' ? e.ts : null))
            .filter((ts) => ts !== null);

        let setSeconds = null;
        if (setStamps.length >= 2) {
            // Past sets: use the audit-derived duration (frozen).
            // Live set: extend with the wall-clock delta since the
            // last scoring event so the counter ticks between rallies.
            const first = Math.min.apply(null, setStamps);
            const last = Math.max.apply(null, setStamps);
            if (isLiveSet) {
                setSeconds = (Date.now() / 1000) - first;
            } else {
                setSeconds = last - first;
            }
        } else if (setDurations[String(setNum)] != null) {
            setSeconds = Number(setDurations[String(setNum)]) || 0;
        }

        let matchSeconds = null;
        if (typeof match.match_started_at === 'number') {
            matchSeconds = (Date.now() / 1000) - match.match_started_at;
        } else {
            // Fallback: sum the per-set durations.
            let total = 0;
            for (const v of Object.values(setDurations)) {
                const n = Number(v);
                if (Number.isFinite(n) && n > 0) total += n;
            }
            if (total > 0) matchSeconds = total;
        }

        if (setSeconds == null && matchSeconds == null) {
            wrap.setAttribute('hidden', 'hidden');
            return;
        }
        wrap.removeAttribute('hidden');
        setEl.textContent = setSeconds != null ? formatTime(setSeconds) : '—';
        matchEl.textContent = matchSeconds != null ? formatTime(matchSeconds) : '—';
    }

    function renderAlerts(broadcast) {
        const oc = broadcast.overlay_control || {};
        const info = oc.match_point_info || {};
        const switchInfo = oc.beach_side_switch || null;

        // Match point takes visual priority over set point on each
        // side, mirroring the React control UI rule. The spectator
        // shows at most one badge per team.
        const team1Match = !!info.team_1_match_point;
        const team2Match = !!info.team_2_match_point;
        const team1Set = !!info.team_1_set_point && !team1Match;
        const team2Set = !!info.team_2_set_point && !team2Match;
        setHidden('alert-team1-match-point', !team1Match);
        setHidden('alert-team2-match-point', !team2Match);
        setHidden('alert-team1-set-point', !team1Set);
        setHidden('alert-team2-set-point', !team2Set);

        const switchBadge = $('alert-side-switch');
        const switchText = $('alert-side-switch-text');
        if (!switchBadge || !switchText) return;
        if (!switchInfo) {
            switchBadge.setAttribute('hidden', 'hidden');
            switchText.textContent = '';
            switchBadge.classList.remove('pending');
            return;
        }
        const remaining = Math.max(0, switchInfo.points_until_switch || 0);
        const pending = !!switchInfo.is_switch_pending;
        if (pending) {
            switchText.textContent = t('alert.switchNow');
            switchBadge.classList.add('pending');
            switchBadge.removeAttribute('hidden');
            return;
        }
        if (remaining > 0 && remaining <= 5) {
            const key = remaining === 1 ? 'alert.switchIn' : 'alert.switchInPlural';
            switchText.textContent = t(key, { n: remaining });
            switchBadge.classList.remove('pending');
            switchBadge.removeAttribute('hidden');
        } else {
            switchBadge.setAttribute('hidden', 'hidden');
            switchText.textContent = '';
            switchBadge.classList.remove('pending');
        }
    }

    // ── Render: scoreboard ─────────────────────────────────────────

    function renderScoreboard(broadcast) {
        const home = broadcast.team_home || {};
        const away = broadcast.team_away || {};
        const match = broadcast.match_info || {};

        const homeColor = home.color_primary || '#E21836';
        const awayColor = away.color_primary || '#0047AB';
        document.documentElement.style.setProperty('--team1-color', homeColor);
        document.documentElement.style.setProperty('--team2-color', awayColor);

        setText('team1-name', home.name || 'Team 1');
        setText('team2-name', away.name || 'Team 2');
        setText('team1-sets', home.sets_won || 0);
        setText('team2-sets', away.sets_won || 0);
        setText('team1-score', home.points || 0);
        setText('team2-score', away.points || 0);
        setLogo('team1-logo', home.logo_url);
        setLogo('team2-logo', away.logo_url);
        setHidden('team1-serve', !home.serving);
        setHidden('team2-serve', !away.serving);

        // Timeouts pips. The CSS handles the visual fill via the
        // ``data-used`` attribute (0/1/2).
        const pipsHome = $('team1-timeouts');
        const pipsAway = $('team2-timeouts');
        if (pipsHome) pipsHome.dataset.used = String(
            Math.max(0, Math.min(2, home.timeouts_taken || 0)),
        );
        if (pipsAway) pipsAway.dataset.used = String(
            Math.max(0, Math.min(2, away.timeouts_taken || 0)),
        );

        setText('set-label', t('board.setLabel', { set: match.current_set || 1 }));
        setText(
            'match-title',
            `${home.name || 'Team 1'} · ${away.name || 'Team 2'}`,
        );
        // Legend swatches mirror the *resolved* chart colours so any
        // collision fallback applied in renderSetChart shows up in
        // the legend too. We just sync the names here; the swatch
        // colours are written by renderSetChart.
        setText('legend-name-home', home.name || 'Team 1');
        setText('legend-name-away', away.name || 'Team 2');
    }

    // ── Render: set history table (clickable rows) ─────────────────

    function renderHistory(broadcast) {
        const home = broadcast.team_home || {};
        const away = broadcast.team_away || {};
        const match = broadcast.match_info || {};
        const best = Math.max(1, Math.min(7, match.best_of_sets || 5));
        const currentSet = match.current_set || 1;
        const viewed = effectiveSet();

        const headRow = $('history-head');
        const homeRow = $('history-row-home');
        const awayRow = $('history-row-away');
        if (!headRow || !homeRow || !awayRow) return;
        headRow.textContent = '';
        homeRow.textContent = '';
        awayRow.textContent = '';

        const teamHeader = document.createElement('th');
        teamHeader.textContent = t('history.team');
        headRow.appendChild(teamHeader);

        const homeLabel = document.createElement('td');
        homeLabel.className = 'team-cell';
        homeLabel.textContent = home.name || 'Team 1';
        homeRow.appendChild(homeLabel);

        const awayLabel = document.createElement('td');
        awayLabel.className = 'team-cell';
        awayLabel.textContent = away.name || 'Team 2';
        awayRow.appendChild(awayLabel);

        for (let i = 1; i <= best; i += 1) {
            const th = document.createElement('th');
            th.className = 'chart-cell';
            th.textContent = `S${i}`;
            if (i === viewed) th.classList.add('active-set');
            th.addEventListener('click', () => switchToSet(i, currentSet));
            headRow.appendChild(th);

            const homeCell = document.createElement('td');
            const awayCell = document.createElement('td');
            const homeScore = (home.set_history || {})[`set_${i}`] || 0;
            const awayScore = (away.set_history || {})[`set_${i}`] || 0;
            homeCell.textContent = homeScore;
            awayCell.textContent = awayScore;
            homeCell.className = 'chart-cell';
            awayCell.className = 'chart-cell';
            if (i === currentSet) {
                homeCell.classList.add('live-cell');
                awayCell.classList.add('live-cell');
            }
            if (i === viewed) {
                homeCell.classList.add('active-set');
                awayCell.classList.add('active-set');
            }
            homeCell.addEventListener('click', () => switchToSet(i, currentSet));
            awayCell.addEventListener('click', () => switchToSet(i, currentSet));
            homeRow.appendChild(homeCell);
            awayRow.appendChild(awayCell);
        }
    }

    // ── Render: live stats ─────────────────────────────────────────

    /*
     * Per-team stats grid. Each row has three cells (home value /
     * label / away value). Rows where neither team has a value
     * collapse via the ``data-empty="true"`` flag so the panel never
     * shows "—" for both columns. Stats that only apply to one team
     * (current streak, longest streak, comeback) leave the other
     * team's cell muted with an em-dash so the column alignment
     * stays stable across consecutive renders.
     */
    function setTeamCell(id, value, muted) {
        const el = $(id);
        if (!el) return;
        el.textContent = value;
        if (muted) el.classList.add('muted');
        else el.classList.remove('muted');
    }

    function renderStats(broadcast) {
        const oc = broadcast.overlay_control || {};
        const stats = oc.stats || {};
        const services = stats.services || {};
        const home = broadcast.team_home || {};
        const away = broadcast.team_away || {};

        // Per-set streak / longest streak / comeback. The match-wide
        // versions in ``stats.*`` aggregate across the whole match,
        // which doesn't match the "currently viewed set" frame the
        // chart and history table already use. Walk the events for
        // the viewed set client-side so the panel re-scopes when the
        // viewer steps through previous sets.
        const setNum = effectiveSet();
        const bySet = oc.points_by_set || {};
        const setEvents = bySet[String(setNum)] || bySet[setNum] || [];
        const perSet = perSetStreakAndComeback(setEvents);
        const cs = perSet.currentStreak;
        const ls = perSet.longestStreak;
        const comeback = perSet.comeback;

        // ── Total points per team ──
        // ``set_history`` carries every set's running score, including
        // the live set, so summing it directly is the per-team match
        // total. Adding ``team.points`` would double-count the live set.
        const liveHome = sumSetHistory(home.set_history);
        const liveAway = sumSetHistory(away.set_history);
        const haveTotals = (liveHome + liveAway) > 0;
        if (haveTotals) {
            setTeamCell('stat-totals-home', String(liveHome), false);
            setTeamCell('stat-totals-away', String(liveAway), false);
        }
        toggleStatRow('stat-row-totals', !haveTotals);

        // ── Services won (won / served per team) ──
        const svcHome = services[1] || services['1'] || {};
        const svcAway = services[2] || services['2'] || {};
        const haveServices = (svcHome.served || 0) + (svcAway.served || 0) > 0;
        if (haveServices) {
            setTeamCell(
                'stat-services-home',
                t('stats.services.cell', {
                    won: svcHome.won || 0, total: svcHome.served || 0,
                }),
                (svcHome.served || 0) === 0,
            );
            setTeamCell(
                'stat-services-away',
                t('stats.services.cell', {
                    won: svcAway.won || 0, total: svcAway.served || 0,
                }),
                (svcAway.served || 0) === 0,
            );
        }
        toggleStatRow('stat-row-services', !haveServices);

        // ── Current streak (only the team that has it) ──
        const haveStreak = cs.team && (cs.n || 0) >= 2;
        if (haveStreak) {
            const homeVal = cs.team === 1 ? t('stats.streak.cell', { n: cs.n }) : '—';
            const awayVal = cs.team === 2 ? t('stats.streak.cell', { n: cs.n }) : '—';
            setTeamCell('stat-streak-home', homeVal, cs.team !== 1);
            setTeamCell('stat-streak-away', awayVal, cs.team !== 2);
        }
        toggleStatRow('stat-row-streak', !haveStreak);

        // ── Longest streak (only the team that holds it) ──
        const haveLongest = ls.team && (ls.n || 0) >= 3 && ls.n > (cs.n || 0);
        if (haveLongest) {
            const homeVal = ls.team === 1 ? t('stats.streak.cell', { n: ls.n }) : '—';
            const awayVal = ls.team === 2 ? t('stats.streak.cell', { n: ls.n }) : '—';
            setTeamCell('stat-longest-home', homeVal, ls.team !== 1);
            setTeamCell('stat-longest-away', awayVal, ls.team !== 2);
        }
        toggleStatRow('stat-row-longest', !haveLongest);

        // ── Partial comeback (only the team that pulled it off) ──
        // Scoped to the viewed set.
        const haveComeback = !!comeback.team && (comeback.n || 0) >= 3;
        if (haveComeback) {
            const homeVal = comeback.team === 1
                ? t('stats.comeback.cell', { n: comeback.n }) : '—';
            const awayVal = comeback.team === 2
                ? t('stats.comeback.cell', { n: comeback.n }) : '—';
            setTeamCell('stat-comeback-home', homeVal, comeback.team !== 1);
            setTeamCell('stat-comeback-away', awayVal, comeback.team !== 2);
        }
        toggleStatRow('stat-row-comeback', !haveComeback);
    }

    function toggleStatRow(rowId, empty) {
        const row = $(rowId);
        if (!row) return;
        row.dataset.empty = empty ? 'true' : 'false';
    }

    function sumSetHistory(setHistory) {
        if (!setHistory || typeof setHistory !== 'object') return 0;
        let total = 0;
        for (const v of Object.values(setHistory)) {
            if (typeof v === 'number') total += v;
        }
        return total;
    }

    /*
     * Walk the events for a single set and compute streak / longest /
     * partial-comeback indicators scoped to that set. The match-level
     * versions in ``compute_live_stats`` aggregate across all sets,
     * which is the wrong scope for the "currently viewed set" panel.
     *
     * Returns:
     *   {
     *     currentStreak: {team, n},   // trailing run of consecutive
     *                                 // ``add_point`` by one team
     *     longestStreak: {team, n},   // longest such run in this set
     *     comeback:      {team, n},   // largest deficit reduction by
     *                                 // one team within this set
     *   }
     */
    function perSetStreakAndComeback(events) {
        const out = {
            currentStreak: { team: null, n: 0 },
            longestStreak: { team: null, n: 0 },
            comeback: { team: null, n: 0 },
        };
        if (!Array.isArray(events) || events.length === 0) return out;

        let streakTeam = null;
        let streakN = 0;
        const cb = {
            1: { peak: 0, minAfter: 0, recovery: 0 },
            2: { peak: 0, minAfter: 0, recovery: 0 },
        };
        for (const ev of events) {
            const team = ev.team;
            // Manual ``set_score`` overrides break the streak — same
            // semantic as the backend's _current_streak helper.
            if (ev.action === 'set_score') {
                streakTeam = null;
                streakN = 0;
                continue;
            }
            if (team !== 1 && team !== 2) continue;
            if (team === streakTeam) {
                streakN += 1;
            } else {
                streakTeam = team;
                streakN = 1;
            }
            if (streakN > out.longestStreak.n) {
                out.longestStreak = { team: streakTeam, n: streakN };
            }
            const score = Array.isArray(ev.score) ? ev.score : [0, 0];
            const s1 = score[0] || 0;
            const s2 = score[1] || 0;
            for (const t of [1, 2]) {
                const myScore = t === 1 ? s1 : s2;
                const rivalScore = t === 1 ? s2 : s1;
                const deficit = rivalScore - myScore;
                if (deficit > cb[t].peak) {
                    cb[t].peak = deficit;
                    cb[t].minAfter = deficit;
                } else if (cb[t].peak > 0 && deficit < cb[t].minAfter) {
                    cb[t].minAfter = deficit;
                    const rec = cb[t].peak - cb[t].minAfter;
                    if (rec > cb[t].recovery) cb[t].recovery = rec;
                }
            }
        }
        out.currentStreak = streakTeam !== null
            ? { team: streakTeam, n: streakN }
            : { team: null, n: 0 };
        const bestRec = Math.max(cb[1].recovery, cb[2].recovery);
        if (bestRec > 0) {
            const team = cb[1].recovery >= cb[2].recovery ? 1 : 2;
            out.comeback = { team: team, n: bestRec };
        }
        return out;
    }

    /*
     * Format a duration in seconds as ``M:SS`` (or ``H:MM:SS`` once
     * it crosses the hour mark). The hour branch matters for long
     * indoor matches that frequently run past 60 min total elapsed.
     * Single helper shared by the scoreboard timers and the chart's
     * X-axis labels so both surfaces stay consistent.
     */
    function formatTime(seconds) {
        const total = Math.max(0, Math.floor(seconds));
        const h = Math.floor(total / 3600);
        const m = Math.floor((total % 3600) / 60);
        const s = total % 60;
        const ss = s < 10 ? '0' + s : String(s);
        if (h > 0) {
            const mm = m < 10 ? '0' + m : String(m);
            return `${h}:${mm}:${ss}`;
        }
        return `${m}:${ss}`;
    }

    // ── Render: set progression chart ──────────────────────────────

    /*
     * Set progression chart.
     *
     * X axis: real time elapsed since the first event of the set. We
     *   prefer this over event index because it surfaces the rhythm of
     *   the set — a 90s sideout streak and a 5s ace burst now occupy
     *   visibly different horizontal spans. Falls back to event index
     *   only when no event carries a usable timestamp.
     * Y axis: running point total per team, with up to 5 dashed grid
     *   lines and tick labels in a high-contrast colour.
     * Markers: small team-coloured circles at every scoring event so
     *   the viewer can count exact rallies, plus dashed vertical
     *   "T" badges where each team called a timeout.
     */
    function renderSetChart(broadcast) {
        const empty = $('set-chart-empty');
        const svg = $('set-chart-svg');
        const lineHome = $('set-chart-line-home');
        const lineAway = $('set-chart-line-away');
        const grid = $('set-chart-grid');
        const navLabel = $('set-nav-label');
        if (!svg || !lineHome || !lineAway || !empty || !grid || !navLabel) return;

        const oc = broadcast.overlay_control || {};
        const match = broadcast.match_info || {};
        const rawHomeColor = (broadcast.team_home || {}).color_primary || '#E21836';
        const rawAwayColor = (broadcast.team_away || {}).color_primary || '#0047AB';
        const resolved = resolveChartColors(rawHomeColor, rawAwayColor);
        const homeColor = resolved.home;
        const awayColor = resolved.away;
        const collision = resolved.collision;
        // Sync legend swatches to whatever colours the chart will use.
        // When collision fired, the away swatch picks up the fallback
        // so the viewer can match line ↔ team without surprises.
        const swHome = $('legend-swatch-home');
        if (swHome) swHome.style.background = homeColor;
        const swAway = $('legend-swatch-away');
        if (swAway) swAway.style.background = awayColor;
        const currentSet = match.current_set || 1;
        const bySet = oc.points_by_set || {};
        const timeoutsBySet = oc.timeouts_by_set || {};
        const setNum = effectiveSet();

        // Nav header.
        const isLive = setNum === currentSet;
        navLabel.textContent = t(
            isLive ? 'chart.nav.setLive' : 'chart.nav.set',
            { set: setNum },
        );

        const best = Math.max(1, Math.min(7, match.best_of_sets || 5));
        const prevBtn = $('set-prev');
        const nextBtn = $('set-next');
        if (prevBtn) prevBtn.disabled = setNum <= 1;
        if (nextBtn) nextBtn.disabled = setNum >= best || (state.viewMode === 'live');

        const events = bySet[String(setNum)] || bySet[setNum] || [];
        const timeouts = timeoutsBySet[String(setNum)] || timeoutsBySet[setNum] || [];

        // Clear previous render before deciding empty-state. The
        // earlier ``grid.textContent = ''`` only cleared the grid; we
        // also need to drop dot markers and timeout overlays so the
        // chart doesn't pile up between renders.
        Array.from(svg.querySelectorAll('.set-chart-dot, .set-chart-timeout')).forEach(
            (el) => el.remove(),
        );
        grid.textContent = '';

        if (!events.length) {
            svg.setAttribute('hidden', 'hidden');
            empty.removeAttribute('hidden');
            lineHome.setAttribute('d', '');
            lineAway.setAttribute('d', '');
            return;
        }

        svg.removeAttribute('hidden');
        empty.setAttribute('hidden', 'hidden');

        const W = 600;
        const H = 180;
        const PAD_L = 28;
        const PAD_R = 12;
        const PAD_T = 14;
        const PAD_B = 22;
        const innerW = W - PAD_L - PAD_R;
        const innerH = H - PAD_T - PAD_B;

        // Time anchor: earliest event in the set (events arrive in
        // chronological order). Use the same anchor for the synthetic
        // 0-0 baseline so the line starts on the left edge.
        const eventTimes = events
            .map((p) => (typeof p.ts === 'number' ? p.ts : null))
            .filter((ts) => ts !== null);
        const useTimeAxis = eventTimes.length >= 2;
        const minTs = useTimeAxis ? Math.min.apply(null, eventTimes) : 0;
        const maxTs = useTimeAxis ? Math.max.apply(null, eventTimes) : 1;
        const timeSpan = Math.max(1, maxTs - minTs);

        // Series: synthetic 0-0 baseline at minTs (or idx 0), then
        // each event with its own time/score.
        const series = [{
            ts: minTs,
            idx: 0,
            score: [0, 0],
        }];
        events.forEach((p, i) => {
            const s = Array.isArray(p.score) ? p.score : [0, 0];
            const ts = typeof p.ts === 'number' ? p.ts : minTs;
            series.push({
                ts: ts,
                idx: i + 1,
                score: [s[0] || 0, s[1] || 0],
            });
        });
        const maxIdx = Math.max(1, series.length - 1);
        const maxScore = Math.max(
            1,
            ...series.map((p) => Math.max(p.score[0], p.score[1])),
        );

        function projectX(point) {
            if (useTimeAxis) {
                return PAD_L + ((point.ts - minTs) / timeSpan) * innerW;
            }
            return PAD_L + (point.idx / maxIdx) * innerW;
        }
        function projectY(score) {
            return PAD_T + innerH - (score / maxScore) * innerH;
        }

        function buildPath(teamIdx) {
            return series
                .map((p, i) => {
                    const x = projectX(p);
                    const y = projectY(p.score[teamIdx]);
                    return `${i === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`;
                })
                .join(' ');
        }

        lineHome.setAttribute('d', buildPath(0));
        lineAway.setAttribute('d', buildPath(1));
        lineHome.setAttribute('stroke', homeColor);
        lineAway.setAttribute('stroke', awayColor);
        // Collision belt-and-braces: dash the away line so two
        // similar colours still parse as two distinct traces. Cleared
        // back to solid when there's no collision so the default
        // appearance remains unchanged for the common case.
        lineHome.removeAttribute('stroke-dasharray');
        if (collision) {
            lineAway.setAttribute('stroke-dasharray', '6 4');
        } else {
            lineAway.removeAttribute('stroke-dasharray');
        }

        // Y-axis ticks: up to 5 evenly spaced, deduped early in the set.
        const tickCount = Math.min(5, Math.max(2, maxScore + 1));
        const seen = new Set();
        for (let i = 0; i < tickCount; i += 1) {
            const value = Math.round((i / (tickCount - 1)) * maxScore);
            if (seen.has(value)) continue;
            seen.add(value);
            const y = projectY(value);
            const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
            line.setAttribute('x1', String(PAD_L));
            line.setAttribute('x2', String(W - PAD_R));
            line.setAttribute('y1', y.toFixed(1));
            line.setAttribute('y2', y.toFixed(1));
            grid.appendChild(line);

            const text = document.createElementNS('http://www.w3.org/2000/svg', 'text');
            text.setAttribute('x', '6');
            text.setAttribute('y', (y + 4).toFixed(1));
            text.textContent = String(value);
            grid.appendChild(text);
        }

        // X-axis: render a baseline + time labels at min / mid / max
        // so the viewer can see the chart actually spans real time.
        const baseY = projectY(0);
        const baseline = document.createElementNS('http://www.w3.org/2000/svg', 'line');
        baseline.setAttribute('x1', String(PAD_L));
        baseline.setAttribute('x2', String(W - PAD_R));
        baseline.setAttribute('y1', baseY.toFixed(1));
        baseline.setAttribute('y2', baseY.toFixed(1));
        baseline.setAttribute('stroke-dasharray', '0');
        grid.appendChild(baseline);

        if (useTimeAxis) {
            const labelY = baseY + 14;
            const stops = [0, 0.5, 1];
            for (const frac of stops) {
                const x = PAD_L + frac * innerW;
                const ts = minTs + frac * timeSpan;
                const elapsedS = Math.max(0, Math.round(ts - minTs));
                const text = document.createElementNS('http://www.w3.org/2000/svg', 'text');
                text.setAttribute('x', x.toFixed(1));
                text.setAttribute('y', labelY.toFixed(1));
                text.setAttribute('text-anchor',
                    frac === 0 ? 'start' : (frac === 1 ? 'end' : 'middle'));
                text.textContent = formatTime(elapsedS);
                grid.appendChild(text);
            }
        }

        // Data-point dots — one circle per scoring event on each
        // team's line. Skip the synthetic baseline at index 0.
        const dotR = 2.6;
        for (let i = 1; i < series.length; i += 1) {
            const p = series[i];
            const x = projectX(p);
            // Home dot
            const cHome = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
            cHome.classList.add('set-chart-dot', 'set-chart-dot-home');
            cHome.setAttribute('cx', x.toFixed(1));
            cHome.setAttribute('cy', projectY(p.score[0]).toFixed(1));
            cHome.setAttribute('r', String(dotR));
            cHome.setAttribute('fill', homeColor);
            svg.appendChild(cHome);
            // Away dot
            const cAway = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
            cAway.classList.add('set-chart-dot', 'set-chart-dot-away');
            cAway.setAttribute('cx', x.toFixed(1));
            cAway.setAttribute('cy', projectY(p.score[1]).toFixed(1));
            cAway.setAttribute('r', String(dotR));
            cAway.setAttribute('fill', awayColor);
            svg.appendChild(cAway);
        }

        // Timeout markers. Only meaningful when we have a time axis;
        // otherwise we drop them (their order vs. points would be a
        // fiction). Each timeout = a dashed vertical line in the
        // calling team's colour + a "T" badge at the top.
        if (useTimeAxis) {
            for (const to of timeouts) {
                if (typeof to.ts !== 'number') continue;
                if (to.ts < minTs || to.ts > maxTs) continue;
                const team = to.team === 2 ? 2 : 1;
                const color = team === 1 ? homeColor : awayColor;
                const x = PAD_L + ((to.ts - minTs) / timeSpan) * innerW;
                const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
                line.classList.add('set-chart-timeout', 'set-chart-timeout-line');
                line.setAttribute('x1', x.toFixed(1));
                line.setAttribute('x2', x.toFixed(1));
                line.setAttribute('y1', String(PAD_T));
                line.setAttribute('y2', baseY.toFixed(1));
                line.setAttribute('stroke', color);
                svg.appendChild(line);

                const badge = document.createElementNS('http://www.w3.org/2000/svg', 'text');
                badge.classList.add('set-chart-timeout', 'set-chart-timeout-badge');
                badge.setAttribute('x', x.toFixed(1));
                badge.setAttribute('y', String(PAD_T - 2));
                badge.setAttribute('text-anchor', 'middle');
                badge.setAttribute('fill', color);
                badge.textContent = t('chart.timeoutBadge');
                svg.appendChild(badge);
            }
        }
    }

    // ── Set navigation ─────────────────────────────────────────────

    function switchToSet(setNum, currentSet) {
        if (setNum < 1) return;
        if (setNum === currentSet) {
            state.viewMode = 'live';
        } else {
            state.viewMode = 'frozen';
            state.viewedSet = setNum;
        }
        renderAll();
    }

    function wireNavButtons() {
        const prev = $('set-prev');
        const next = $('set-next');
        if (prev) prev.addEventListener('click', () => {
            const broadcast = state.lastBroadcast || {};
            const currentSet = (broadcast.match_info || {}).current_set || 1;
            switchToSet(Math.max(1, effectiveSet() - 1), currentSet);
        });
        if (next) next.addEventListener('click', () => {
            const broadcast = state.lastBroadcast || {};
            const currentSet = (broadcast.match_info || {}).current_set || 1;
            const best = Math.max(
                1, Math.min(7, (broadcast.match_info || {}).best_of_sets || 5),
            );
            switchToSet(Math.min(best, effectiveSet() + 1), currentSet);
        });
    }

    // ── Top-level render ───────────────────────────────────────────

    function renderAll() {
        const broadcast = state.lastBroadcast;
        if (!broadcast) return;
        renderRulesSummary(broadcast);
        renderAlerts(broadcast);
        renderScoreboard(broadcast);
        renderTimers(broadcast);
        renderHistory(broadcast);
        renderStats(broadcast);
        renderSetChart(broadcast);
    }

    function render(broadcast) {
        if (!broadcast || typeof broadcast !== 'object') return;
        state.lastBroadcast = broadcast;
        // While in "live" mode the viewed set tracks the current set.
        if (state.viewMode === 'live') {
            state.viewedSet = (broadcast.match_info || {}).current_set || 1;
        }
        renderAll();
    }

    // ── WebSocket lifecycle ────────────────────────────────────────

    let ws = null;
    let reconnectAttempts = 0;
    let reconnectTimer = null;

    function connect() {
        try {
            ws = new WebSocket(wsUrl);
        } catch (err) {
            setStatus(t('status.error'), 'offline');
            scheduleReconnect();
            return;
        }
        setStatus(t('status.connecting'));

        ws.addEventListener('open', () => {
            setStatus(t('status.online'), 'online');
            reconnectAttempts = 0;
        });
        ws.addEventListener('message', (event) => {
            try {
                render(JSON.parse(event.data));
            } catch (_err) {
                /* ignore malformed frames */
            }
        });
        ws.addEventListener('close', () => {
            setStatus(t('status.offline'), 'offline');
            scheduleReconnect();
        });
        ws.addEventListener('error', () => {
            /* close handler will run; nothing extra to do here */
        });
    }

    function scheduleReconnect() {
        if (reconnectTimer) return;
        const delay = Math.min(15000, 1000 * Math.pow(2, reconnectAttempts));
        reconnectAttempts += 1;
        reconnectTimer = setTimeout(() => {
            reconnectTimer = null;
            connect();
        }, delay);
    }

    // ── Init ───────────────────────────────────────────────────────

    applyStaticTranslations();
    wireNavButtons();
    connect();

    // Tick the set + match elapsed counters every second so they
    // keep moving between scoring events. Re-rendering just the
    // timers is cheap (two text nodes); the full broadcast render
    // still runs only when the WS pushes a new state.
    setInterval(() => {
        const broadcast = state.lastBroadcast;
        if (!broadcast) return;
        try { renderTimers(broadcast); } catch (_e) { /* ignore */ }
    }, 1000);
})();
