/*
 * Spectator (follow) page — read-only WebSocket consumer for
 * /follow/{output_key}. Subscribes to the same broadcast OBS uses
 * and renders into a mobile-first layout. Vanilla JS, no deps.
 */

(function () {
    'use strict';

    // ── i18n ────────────────────────────────────────────────────────
    //
    // We pick the language from the ``?lang=`` query string when present
    // (so a share link generated by the operator can preserve their UI
    // locale), then fall back to ``navigator.language``, then English.
    // The translation tables mirror the keys used in the template /
    // JS and the React-side ``i18n.tsx``.
    const TRANSLATIONS = {
        en: {
            'status.connecting': 'connecting…',
            'status.online': 'live',
            'status.offline': 'reconnecting…',
            'status.error': 'connection error',
            'board.sets': 'Sets',
            'board.timeouts': 'T/O',
            'board.setLabel': 'Set {set}',
            'rules.mode.indoor': 'Indoor',
            'rules.mode.beach': 'Beach',
            'rules.bestOf': 'Best of {n}',
            'rules.points': '{regular} · {last} in deciding set',
            'rules.switchEvery': 'Side switch every {n} pts',
            'alert.setPoint': 'Set point',
            'alert.matchPoint': 'Match point',
            'alert.switchIn': 'Switch in {n} pt',
            'alert.switchInPlural': 'Switch in {n} pts',
            'alert.switchNow': 'Side switch now',
            'chart.title': 'Set progression',
            'chart.empty': 'Waiting for the first point of the set…',
            'chart.nav.set': 'Set {set}',
            'chart.nav.setLive': 'Set {set} · live',
            'chart.timeoutBadge': 'T',
            'history.team': 'Team',
            'stats.totals': 'Total points',
            'stats.services.label': 'Services won',
            'stats.services.value': '{home}: {hWon}/{hTotal} · {away}: {aWon}/{aTotal}',
            'stats.streak.label': 'Streak',
            'stats.streak.value': '{name} · {n} in a row',
            'stats.comeback.label': 'Comeback',
            'stats.comeback.value': '{name} · -{n}',
            'footer.label': 'Live updates',
        },
        es: {
            'status.connecting': 'conectando…',
            'status.online': 'en directo',
            'status.offline': 'reconectando…',
            'status.error': 'error de conexión',
            'board.sets': 'Sets',
            'board.timeouts': 'T/M',
            'board.setLabel': 'Set {set}',
            'rules.mode.indoor': 'Indoor',
            'rules.mode.beach': 'Playa',
            'rules.bestOf': 'Al mejor de {n}',
            'rules.points': '{regular} · {last} en set decisivo',
            'rules.switchEvery': 'Cambio cada {n} pts',
            'alert.setPoint': 'Punto de set',
            'alert.matchPoint': 'Punto de partido',
            'alert.switchIn': 'Cambio en {n} pt',
            'alert.switchInPlural': 'Cambio en {n} pts',
            'alert.switchNow': 'Cambiar de campo',
            'chart.title': 'Evolución del set',
            'chart.empty': 'Esperando el primer punto del set…',
            'chart.nav.set': 'Set {set}',
            'chart.nav.setLive': 'Set {set} · en juego',
            'chart.timeoutBadge': 'TM',
            'history.team': 'Equipo',
            'stats.totals': 'Puntos totales',
            'stats.services.label': 'Saques ganados',
            'stats.services.value': '{home}: {hWon}/{hTotal} · {away}: {aWon}/{aTotal}',
            'stats.streak.label': 'Racha',
            'stats.streak.value': '{name} · {n} seguidos',
            'stats.comeback.label': 'Remontada',
            'stats.comeback.value': '{name} · -{n}',
            'footer.label': 'Actualización en vivo',
        },
        pt: {
            'status.connecting': 'a ligar…',
            'status.online': 'em direto',
            'status.offline': 'a religar…',
            'status.error': 'erro de ligação',
            'board.sets': 'Sets',
            'board.timeouts': 'T/M',
            'board.setLabel': 'Set {set}',
            'rules.mode.indoor': 'Indoor',
            'rules.mode.beach': 'Praia',
            'rules.bestOf': 'À melhor de {n}',
            'rules.points': '{regular} · {last} no set decisivo',
            'rules.switchEvery': 'Mudança cada {n} pts',
            'alert.setPoint': 'Ponto de set',
            'alert.matchPoint': 'Ponto de partida',
            'alert.switchIn': 'Mudança em {n} pt',
            'alert.switchInPlural': 'Mudança em {n} pts',
            'alert.switchNow': 'Mudar de campo',
            'chart.title': 'Evolução do set',
            'chart.empty': 'À espera do primeiro ponto do set…',
            'chart.nav.set': 'Set {set}',
            'chart.nav.setLive': 'Set {set} · ao vivo',
            'chart.timeoutBadge': 'TM',
            'history.team': 'Equipa',
            'stats.totals': 'Pontos totais',
            'stats.services.label': 'Serviços ganhos',
            'stats.services.value': '{home}: {hWon}/{hTotal} · {away}: {aWon}/{aTotal}',
            'stats.streak.label': 'Sequência',
            'stats.streak.value': '{name} · {n} seguidos',
            'stats.comeback.label': 'Recuperação',
            'stats.comeback.value': '{name} · -{n}',
            'footer.label': 'Atualizações ao vivo',
        },
        it: {
            'status.connecting': 'connessione…',
            'status.online': 'in diretta',
            'status.offline': 'riconnessione…',
            'status.error': 'errore di connessione',
            'board.sets': 'Set',
            'board.timeouts': 'T/O',
            'board.setLabel': 'Set {set}',
            'rules.mode.indoor': 'Indoor',
            'rules.mode.beach': 'Beach',
            'rules.bestOf': 'Al meglio dei {n}',
            'rules.points': '{regular} · {last} nel set decisivo',
            'rules.switchEvery': 'Cambio campo ogni {n} pt',
            'alert.setPoint': 'Set point',
            'alert.matchPoint': 'Match point',
            'alert.switchIn': 'Cambio tra {n} pt',
            'alert.switchInPlural': 'Cambio tra {n} pt',
            'alert.switchNow': 'Cambiare campo',
            'chart.title': 'Andamento del set',
            'chart.empty': 'In attesa del primo punto del set…',
            'chart.nav.set': 'Set {set}',
            'chart.nav.setLive': 'Set {set} · in corso',
            'chart.timeoutBadge': 'TO',
            'history.team': 'Squadra',
            'stats.totals': 'Punti totali',
            'stats.services.label': 'Servizi vinti',
            'stats.services.value': '{home}: {hWon}/{hTotal} · {away}: {aWon}/{aTotal}',
            'stats.streak.label': 'Serie',
            'stats.streak.value': '{name} · {n} di fila',
            'stats.comeback.label': 'Rimonta',
            'stats.comeback.value': '{name} · -{n}',
            'footer.label': 'Aggiornamenti in diretta',
        },
        fr: {
            'status.connecting': 'connexion…',
            'status.online': 'en direct',
            'status.offline': 'reconnexion…',
            'status.error': 'erreur de connexion',
            'board.sets': 'Sets',
            'board.timeouts': 'T/M',
            'board.setLabel': 'Set {set}',
            'rules.mode.indoor': 'Salle',
            'rules.mode.beach': 'Plage',
            'rules.bestOf': 'Au meilleur des {n}',
            'rules.points': '{regular} · {last} dans le set décisif',
            'rules.switchEvery': 'Changement tous les {n} pts',
            'alert.setPoint': 'Balle de set',
            'alert.matchPoint': 'Balle de match',
            'alert.switchIn': 'Changement dans {n} pt',
            'alert.switchInPlural': 'Changement dans {n} pts',
            'alert.switchNow': 'Changer de côté',
            'chart.title': 'Progression du set',
            'chart.empty': 'En attente du premier point du set…',
            'chart.nav.set': 'Set {set}',
            'chart.nav.setLive': 'Set {set} · en jeu',
            'chart.timeoutBadge': 'TM',
            'history.team': 'Équipe',
            'stats.totals': 'Points totaux',
            'stats.services.label': 'Services gagnés',
            'stats.services.value': '{home}: {hWon}/{hTotal} · {away}: {aWon}/{aTotal}',
            'stats.streak.label': 'Série',
            'stats.streak.value': '{name} · {n} d’affilée',
            'stats.comeback.label': 'Remontée',
            'stats.comeback.value': '{name} · -{n}',
            'footer.label': 'Mises à jour en direct',
        },
        de: {
            'status.connecting': 'verbinde…',
            'status.online': 'live',
            'status.offline': 'verbinde neu…',
            'status.error': 'Verbindungsfehler',
            'board.sets': 'Sätze',
            'board.timeouts': 'A/Z',
            'board.setLabel': 'Satz {set}',
            'rules.mode.indoor': 'Halle',
            'rules.mode.beach': 'Beach',
            'rules.bestOf': 'Best of {n}',
            'rules.points': '{regular} · {last} im Entscheidungssatz',
            'rules.switchEvery': 'Seitenwechsel alle {n} Pkt',
            'alert.setPoint': 'Satzball',
            'alert.matchPoint': 'Matchball',
            'alert.switchIn': 'Wechsel in {n} Pkt',
            'alert.switchInPlural': 'Wechsel in {n} Pkt',
            'alert.switchNow': 'Jetzt Seiten wechseln',
            'chart.title': 'Satzverlauf',
            'chart.empty': 'Warte auf den ersten Punkt des Satzes…',
            'chart.nav.set': 'Satz {set}',
            'chart.nav.setLive': 'Satz {set} · live',
            'chart.timeoutBadge': 'AZ',
            'history.team': 'Team',
            'stats.totals': 'Punkte gesamt',
            'stats.services.label': 'Aufschläge gewonnen',
            'stats.services.value': '{home}: {hWon}/{hTotal} · {away}: {aWon}/{aTotal}',
            'stats.streak.label': 'Serie',
            'stats.streak.value': '{name} · {n} in Folge',
            'stats.comeback.label': 'Aufholjagd',
            'stats.comeback.value': '{name} · -{n}',
            'footer.label': 'Live-Updates',
        },
    };

    function pickLanguage() {
        const qs = new URLSearchParams(window.location.search);
        const param = (qs.get('lang') || '').toLowerCase();
        if (param && TRANSLATIONS[param]) return param;
        const nav = (navigator.language || 'en').toLowerCase().split('-')[0];
        return TRANSLATIONS[nav] ? nav : 'en';
    }

    const LANG = pickLanguage();
    document.documentElement.setAttribute('lang', LANG);

    function t(key, args) {
        const bundle = TRANSLATIONS[LANG] || TRANSLATIONS.en;
        let str = bundle[key] || TRANSLATIONS.en[key] || key;
        if (args) {
            for (const k in args) {
                str = str.replace(new RegExp('\\{' + k + '\\}', 'g'), args[k]);
            }
        }
        return str;
    }

    // Apply static ``data-i18n`` / ``data-i18n-tpl`` translations on
    // first paint. Dynamic strings call ``t()`` directly inside their
    // render function.
    function applyStaticTranslations() {
        document.querySelectorAll('[data-i18n]').forEach((el) => {
            const key = el.getAttribute('data-i18n');
            el.textContent = t(key);
        });
        document.querySelectorAll('[data-i18n-tpl]').forEach((el) => {
            const key = el.getAttribute('data-i18n-tpl');
            const args = {};
            for (const attr of el.attributes) {
                if (attr.name.startsWith('data-arg-')) {
                    args[attr.name.slice('data-arg-'.length)] = attr.value;
                }
            }
            el.textContent = t(key, args);
        });
    }

    // ── DOM helpers ────────────────────────────────────────────────

    const OUTPUT_KEY = window.OVERLAY_OUTPUT_KEY;
    if (!OUTPUT_KEY) return;

    const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    const wsUrl = `${protocol}//${window.location.host}/ws/${OUTPUT_KEY}`;
    const $ = (id) => document.getElementById(id);

    function setText(id, value) {
        const el = $(id);
        if (el && el.textContent !== String(value)) el.textContent = String(value);
    }
    function setLogo(id, url) {
        const el = $(id);
        if (!el) return;
        if (!url || typeof url !== 'string') {
            el.removeAttribute('src');
            return;
        }
        // Parse through the URL constructor so we have an authoritative
        // protocol check instead of a regex on the raw string. CodeQL
        // doesn't model regex-based sanitisation; using ``URL`` makes
        // the allow-list explicit and serialises the result back via
        // ``parsed.href`` so any odd characters get encoded.
        let parsed;
        try {
            parsed = new URL(url, window.location.href);
        } catch (_e) {
            el.removeAttribute('src');
            return;
        }
        const proto = parsed.protocol;
        const isHttp = proto === 'http:' || proto === 'https:';
        const isImageData = proto === 'data:' && parsed.pathname.toLowerCase().startsWith('image/');
        if (!isHttp && !isImageData) {
            el.removeAttribute('src');
            return;
        }
        const safe = parsed.href;
        if (el.getAttribute('src') !== safe) el.setAttribute('src', safe);
    }
    function setHidden(id, hidden) {
        const el = $(id);
        if (!el) return;
        if (!!hidden) el.setAttribute('hidden', 'hidden');
        else el.removeAttribute('hidden');
    }
    function setStatus(text, state) {
        const el = $('conn-status');
        if (!el) return;
        el.textContent = text;
        if (state) el.dataset.state = state;
        else delete el.dataset.state;
    }
    function setStatsRow(id, label, value) {
        const row = $(id);
        if (!row) return;
        row.dataset.empty = value ? 'false' : 'true';
        if (!value) { row.textContent = ''; return; }
        row.textContent = '';
        const labelEl = document.createElement('span');
        labelEl.className = 'label';
        labelEl.textContent = label;
        const valueEl = document.createElement('span');
        valueEl.className = 'value';
        valueEl.textContent = value;
        row.appendChild(labelEl);
        row.appendChild(valueEl);
    }

    // ── Local state ────────────────────────────────────────────────

    // ``viewMode``:
    //   * "live" — chart follows the current set being played.
    //   * "frozen" — operator clicked prev/next; chart stays on the
    //     chosen set until "live" is restored (clicking the live set
    //     in the header or hitting Next past the last set).
    const state = {
        viewMode: 'live',
        viewedSet: 1,
        lastBroadcast: null,
    };

    function effectiveSet() {
        const broadcast = state.lastBroadcast || {};
        const currentSet = (broadcast.match_info || {}).current_set || 1;
        if (state.viewMode === 'live') return currentSet;
        return state.viewedSet;
    }

    // ── Render: rules summary + alerts ─────────────────────────────

    function renderRulesSummary(broadcast) {
        const match = broadcast.match_info || {};
        const el = $('rules-summary');
        if (!el) return;
        const mode = match.mode === 'beach' ? 'beach' : 'indoor';
        const sets = match.best_of_sets;
        const reg = match.points_limit;
        const last = match.points_limit_last_set;
        if (!sets || !reg || !last) {
            el.setAttribute('hidden', 'hidden');
            el.textContent = '';
            return;
        }
        const parts = [
            t('rules.mode.' + mode),
            t('rules.bestOf', { n: sets }),
            t('rules.points', { regular: reg, last: last }),
        ];
        if (mode === 'beach') {
            // The side-switch interval is derived the same way the
            // backend does it: 5 if the current set target ≤ 15, else 7.
            // We compute locally so the badge updates immediately on
            // rule changes without waiting for the next score event.
            const currentSet = match.current_set || 1;
            const target = currentSet >= sets ? last : reg;
            const interval = target <= 15 ? 5 : 7;
            parts.push(t('rules.switchEvery', { n: interval }));
        }
        el.textContent = parts.join(' · ');
        el.removeAttribute('hidden');
    }

    function renderAlerts(broadcast) {
        const oc = broadcast.overlay_control || {};
        const info = oc.match_point_info || {};
        const switchInfo = oc.beach_side_switch || null;

        // Match point takes visual priority over set point on each
        // side, mirroring the React control UI rule. The spectator
        // shows at most one badge per team.
        const team1Match = !!info.team_1_match_point;
        const team2Match = !!info.team_2_match_point;
        const team1Set = !!info.team_1_set_point && !team1Match;
        const team2Set = !!info.team_2_set_point && !team2Match;
        setHidden('alert-team1-match-point', !team1Match);
        setHidden('alert-team2-match-point', !team2Match);
        setHidden('alert-team1-set-point', !team1Set);
        setHidden('alert-team2-set-point', !team2Set);

        const switchBadge = $('alert-side-switch');
        const switchText = $('alert-side-switch-text');
        if (!switchBadge || !switchText) return;
        if (!switchInfo) {
            switchBadge.setAttribute('hidden', 'hidden');
            switchText.textContent = '';
            switchBadge.classList.remove('pending');
            return;
        }
        const remaining = Math.max(0, switchInfo.points_until_switch || 0);
        const pending = !!switchInfo.is_switch_pending;
        if (pending) {
            switchText.textContent = t('alert.switchNow');
            switchBadge.classList.add('pending');
            switchBadge.removeAttribute('hidden');
            return;
        }
        if (remaining > 0 && remaining <= 5) {
            const key = remaining === 1 ? 'alert.switchIn' : 'alert.switchInPlural';
            switchText.textContent = t(key, { n: remaining });
            switchBadge.classList.remove('pending');
            switchBadge.removeAttribute('hidden');
        } else {
            switchBadge.setAttribute('hidden', 'hidden');
            switchText.textContent = '';
            switchBadge.classList.remove('pending');
        }
    }

    // ── Render: scoreboard ─────────────────────────────────────────

    function renderScoreboard(broadcast) {
        const home = broadcast.team_home || {};
        const away = broadcast.team_away || {};
        const match = broadcast.match_info || {};

        const homeColor = home.color_primary || '#E21836';
        const awayColor = away.color_primary || '#0047AB';
        document.documentElement.style.setProperty('--team1-color', homeColor);
        document.documentElement.style.setProperty('--team2-color', awayColor);

        setText('team1-name', home.name || 'Team 1');
        setText('team2-name', away.name || 'Team 2');
        setText('team1-sets', home.sets_won || 0);
        setText('team2-sets', away.sets_won || 0);
        setText('team1-score', home.points || 0);
        setText('team2-score', away.points || 0);
        setLogo('team1-logo', home.logo_url);
        setLogo('team2-logo', away.logo_url);
        setHidden('team1-serve', !home.serving);
        setHidden('team2-serve', !away.serving);

        // Timeouts pips. The CSS handles the visual fill via the
        // ``data-used`` attribute (0/1/2).
        const pipsHome = $('team1-timeouts');
        const pipsAway = $('team2-timeouts');
        if (pipsHome) pipsHome.dataset.used = String(
            Math.max(0, Math.min(2, home.timeouts_taken || 0)),
        );
        if (pipsAway) pipsAway.dataset.used = String(
            Math.max(0, Math.min(2, away.timeouts_taken || 0)),
        );

        setText('set-label', t('board.setLabel', { set: match.current_set || 1 }));
        setText(
            'match-title',
            `${home.name || 'Team 1'} · ${away.name || 'Team 2'}`,
        );
        setText('legend-name-home', home.name || 'Team 1');
        setText('legend-name-away', away.name || 'Team 2');
        const swHome = $('legend-swatch-home');
        if (swHome) swHome.style.background = homeColor;
        const swAway = $('legend-swatch-away');
        if (swAway) swAway.style.background = awayColor;
    }

    // ── Render: set history table (clickable rows) ─────────────────

    function renderHistory(broadcast) {
        const home = broadcast.team_home || {};
        const away = broadcast.team_away || {};
        const match = broadcast.match_info || {};
        const best = Math.max(1, Math.min(7, match.best_of_sets || 5));
        const currentSet = match.current_set || 1;
        const viewed = effectiveSet();

        const headRow = $('history-head');
        const homeRow = $('history-row-home');
        const awayRow = $('history-row-away');
        if (!headRow || !homeRow || !awayRow) return;
        headRow.textContent = '';
        homeRow.textContent = '';
        awayRow.textContent = '';

        const teamHeader = document.createElement('th');
        teamHeader.textContent = t('history.team');
        headRow.appendChild(teamHeader);

        const homeLabel = document.createElement('td');
        homeLabel.className = 'team-cell';
        homeLabel.textContent = home.name || 'Team 1';
        homeRow.appendChild(homeLabel);

        const awayLabel = document.createElement('td');
        awayLabel.className = 'team-cell';
        awayLabel.textContent = away.name || 'Team 2';
        awayRow.appendChild(awayLabel);

        for (let i = 1; i <= best; i += 1) {
            const th = document.createElement('th');
            th.className = 'chart-cell';
            th.textContent = `S${i}`;
            if (i === viewed) th.classList.add('active-set');
            th.addEventListener('click', () => switchToSet(i, currentSet));
            headRow.appendChild(th);

            const homeCell = document.createElement('td');
            const awayCell = document.createElement('td');
            const homeScore = (home.set_history || {})[`set_${i}`] || 0;
            const awayScore = (away.set_history || {})[`set_${i}`] || 0;
            homeCell.textContent = homeScore;
            awayCell.textContent = awayScore;
            homeCell.className = 'chart-cell';
            awayCell.className = 'chart-cell';
            if (i === currentSet) {
                homeCell.classList.add('live-cell');
                awayCell.classList.add('live-cell');
            }
            if (i === viewed) {
                homeCell.classList.add('active-set');
                awayCell.classList.add('active-set');
            }
            homeCell.addEventListener('click', () => switchToSet(i, currentSet));
            awayCell.addEventListener('click', () => switchToSet(i, currentSet));
            homeRow.appendChild(homeCell);
            awayRow.appendChild(awayCell);
        }
    }

    // ── Render: live stats ─────────────────────────────────────────

    function renderStats(broadcast) {
        const oc = broadcast.overlay_control || {};
        const stats = oc.stats || {};
        const cs = stats.current_streak || {};
        const pc = stats.partial_comeback || {};
        const services = stats.services || {};
        const home = broadcast.team_home || {};
        const away = broadcast.team_away || {};
        const homeName = home.name || 'Team 1';
        const awayName = away.name || 'Team 2';

        // Row order matches the template: totals → services → streak → comeback.
        if (typeof stats.total_points === 'number' && stats.total_points > 0) {
            setStatsRow('stats-totals', t('stats.totals'), String(stats.total_points));
        } else {
            setStatsRow('stats-totals', '', '');
        }

        const svcHome = services[1] || services['1'] || {};
        const svcAway = services[2] || services['2'] || {};
        const totalServiced = (svcHome.served || 0) + (svcAway.served || 0);
        if (totalServiced > 0) {
            setStatsRow(
                'stats-services',
                t('stats.services.label'),
                t('stats.services.value', {
                    home: homeName,
                    hWon: svcHome.won || 0,
                    hTotal: svcHome.served || 0,
                    away: awayName,
                    aWon: svcAway.won || 0,
                    aTotal: svcAway.served || 0,
                }),
            );
        } else {
            setStatsRow('stats-services', '', '');
        }

        if (cs.team && cs.n >= 2) {
            const name = cs.team === 1 ? homeName : awayName;
            setStatsRow(
                'stats-streak',
                t('stats.streak.label'),
                t('stats.streak.value', { name: name, n: cs.n }),
            );
        } else {
            setStatsRow('stats-streak', '', '');
        }

        const pcHome = pc[1] || pc['1'] || {};
        const pcAway = pc[2] || pc['2'] || {};
        const peak = Math.max(pcHome.deficit || 0, pcAway.deficit || 0);
        if (peak >= 3) {
            const team = (pcHome.deficit || 0) >= (pcAway.deficit || 0) ? 1 : 2;
            const name = team === 1 ? homeName : awayName;
            setStatsRow(
                'stats-comeback',
                t('stats.comeback.label'),
                t('stats.comeback.value', { name: name, n: peak }),
            );
        } else {
            setStatsRow('stats-comeback', '', '');
        }
    }

    // ── Render: set progression chart ──────────────────────────────

    /*
     * Set progression chart.
     *
     * X axis: real time elapsed since the first event of the set. We
     *   prefer this over event index because it surfaces the rhythm of
     *   the set — a 90s sideout streak and a 5s ace burst now occupy
     *   visibly different horizontal spans. Falls back to event index
     *   only when no event carries a usable timestamp.
     * Y axis: running point total per team, with up to 5 dashed grid
     *   lines and tick labels in a high-contrast colour.
     * Markers: small team-coloured circles at every scoring event so
     *   the viewer can count exact rallies, plus dashed vertical
     *   "T" badges where each team called a timeout.
     */
    function renderSetChart(broadcast) {
        const empty = $('set-chart-empty');
        const svg = $('set-chart-svg');
        const lineHome = $('set-chart-line-home');
        const lineAway = $('set-chart-line-away');
        const grid = $('set-chart-grid');
        const navLabel = $('set-nav-label');
        if (!svg || !lineHome || !lineAway || !empty || !grid || !navLabel) return;

        const oc = broadcast.overlay_control || {};
        const match = broadcast.match_info || {};
        const homeColor = (broadcast.team_home || {}).color_primary || '#E21836';
        const awayColor = (broadcast.team_away || {}).color_primary || '#0047AB';
        const currentSet = match.current_set || 1;
        const bySet = oc.points_by_set || {};
        const timeoutsBySet = oc.timeouts_by_set || {};
        const setNum = effectiveSet();

        // Nav header.
        const isLive = setNum === currentSet;
        navLabel.textContent = t(
            isLive ? 'chart.nav.setLive' : 'chart.nav.set',
            { set: setNum },
        );

        const best = Math.max(1, Math.min(7, match.best_of_sets || 5));
        const prevBtn = $('set-prev');
        const nextBtn = $('set-next');
        if (prevBtn) prevBtn.disabled = setNum <= 1;
        if (nextBtn) nextBtn.disabled = setNum >= best || (state.viewMode === 'live');

        const events = bySet[String(setNum)] || bySet[setNum] || [];
        const timeouts = timeoutsBySet[String(setNum)] || timeoutsBySet[setNum] || [];

        // Clear previous render before deciding empty-state. The
        // earlier ``grid.textContent = ''`` only cleared the grid; we
        // also need to drop dot markers and timeout overlays so the
        // chart doesn't pile up between renders.
        Array.from(svg.querySelectorAll('.set-chart-dot, .set-chart-timeout')).forEach(
            (el) => el.remove(),
        );
        grid.textContent = '';

        if (!events.length) {
            svg.setAttribute('hidden', 'hidden');
            empty.removeAttribute('hidden');
            lineHome.setAttribute('d', '');
            lineAway.setAttribute('d', '');
            return;
        }

        svg.removeAttribute('hidden');
        empty.setAttribute('hidden', 'hidden');

        const W = 600;
        const H = 180;
        const PAD_L = 28;
        const PAD_R = 12;
        const PAD_T = 14;
        const PAD_B = 22;
        const innerW = W - PAD_L - PAD_R;
        const innerH = H - PAD_T - PAD_B;

        // Time anchor: earliest event in the set (events arrive in
        // chronological order). Use the same anchor for the synthetic
        // 0-0 baseline so the line starts on the left edge.
        const eventTimes = events
            .map((p) => (typeof p.ts === 'number' ? p.ts : null))
            .filter((ts) => ts !== null);
        const useTimeAxis = eventTimes.length >= 2;
        const minTs = useTimeAxis ? Math.min.apply(null, eventTimes) : 0;
        const maxTs = useTimeAxis ? Math.max.apply(null, eventTimes) : 1;
        const timeSpan = Math.max(1, maxTs - minTs);

        // Series: synthetic 0-0 baseline at minTs (or idx 0), then
        // each event with its own time/score.
        const series = [{
            ts: minTs,
            idx: 0,
            score: [0, 0],
        }];
        events.forEach((p, i) => {
            const s = Array.isArray(p.score) ? p.score : [0, 0];
            const ts = typeof p.ts === 'number' ? p.ts : minTs;
            series.push({
                ts: ts,
                idx: i + 1,
                score: [s[0] || 0, s[1] || 0],
            });
        });
        const maxIdx = Math.max(1, series.length - 1);
        const maxScore = Math.max(
            1,
            ...series.map((p) => Math.max(p.score[0], p.score[1])),
        );

        function projectX(point) {
            if (useTimeAxis) {
                return PAD_L + ((point.ts - minTs) / timeSpan) * innerW;
            }
            return PAD_L + (point.idx / maxIdx) * innerW;
        }
        function projectY(score) {
            return PAD_T + innerH - (score / maxScore) * innerH;
        }

        function buildPath(teamIdx) {
            return series
                .map((p, i) => {
                    const x = projectX(p);
                    const y = projectY(p.score[teamIdx]);
                    return `${i === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`;
                })
                .join(' ');
        }

        lineHome.setAttribute('d', buildPath(0));
        lineAway.setAttribute('d', buildPath(1));
        lineHome.setAttribute('stroke', homeColor);
        lineAway.setAttribute('stroke', awayColor);

        // Y-axis ticks: up to 5 evenly spaced, deduped early in the set.
        const tickCount = Math.min(5, Math.max(2, maxScore + 1));
        const seen = new Set();
        for (let i = 0; i < tickCount; i += 1) {
            const value = Math.round((i / (tickCount - 1)) * maxScore);
            if (seen.has(value)) continue;
            seen.add(value);
            const y = projectY(value);
            const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
            line.setAttribute('x1', String(PAD_L));
            line.setAttribute('x2', String(W - PAD_R));
            line.setAttribute('y1', y.toFixed(1));
            line.setAttribute('y2', y.toFixed(1));
            grid.appendChild(line);

            const text = document.createElementNS('http://www.w3.org/2000/svg', 'text');
            text.setAttribute('x', '6');
            text.setAttribute('y', (y + 4).toFixed(1));
            text.textContent = String(value);
            grid.appendChild(text);
        }

        // X-axis: render a baseline + time labels at min / mid / max
        // so the viewer can see the chart actually spans real time.
        const baseY = projectY(0);
        const baseline = document.createElementNS('http://www.w3.org/2000/svg', 'line');
        baseline.setAttribute('x1', String(PAD_L));
        baseline.setAttribute('x2', String(W - PAD_R));
        baseline.setAttribute('y1', baseY.toFixed(1));
        baseline.setAttribute('y2', baseY.toFixed(1));
        baseline.setAttribute('stroke-dasharray', '0');
        grid.appendChild(baseline);

        if (useTimeAxis) {
            const labelY = baseY + 14;
            const stops = [0, 0.5, 1];
            for (const frac of stops) {
                const x = PAD_L + frac * innerW;
                const ts = minTs + frac * timeSpan;
                const elapsedS = Math.max(0, Math.round(ts - minTs));
                const text = document.createElementNS('http://www.w3.org/2000/svg', 'text');
                text.setAttribute('x', x.toFixed(1));
                text.setAttribute('y', labelY.toFixed(1));
                text.setAttribute('text-anchor',
                    frac === 0 ? 'start' : (frac === 1 ? 'end' : 'middle'));
                text.textContent = formatElapsed(elapsedS);
                grid.appendChild(text);
            }
        }

        // Data-point dots — one circle per scoring event on each
        // team's line. Skip the synthetic baseline at index 0.
        const dotR = 2.6;
        for (let i = 1; i < series.length; i += 1) {
            const p = series[i];
            const x = projectX(p);
            // Home dot
            const cHome = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
            cHome.classList.add('set-chart-dot', 'set-chart-dot-home');
            cHome.setAttribute('cx', x.toFixed(1));
            cHome.setAttribute('cy', projectY(p.score[0]).toFixed(1));
            cHome.setAttribute('r', String(dotR));
            cHome.setAttribute('fill', homeColor);
            svg.appendChild(cHome);
            // Away dot
            const cAway = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
            cAway.classList.add('set-chart-dot', 'set-chart-dot-away');
            cAway.setAttribute('cx', x.toFixed(1));
            cAway.setAttribute('cy', projectY(p.score[1]).toFixed(1));
            cAway.setAttribute('r', String(dotR));
            cAway.setAttribute('fill', awayColor);
            svg.appendChild(cAway);
        }

        // Timeout markers. Only meaningful when we have a time axis;
        // otherwise we drop them (their order vs. points would be a
        // fiction). Each timeout = a dashed vertical line in the
        // calling team's colour + a "T" badge at the top.
        if (useTimeAxis) {
            for (const to of timeouts) {
                if (typeof to.ts !== 'number') continue;
                if (to.ts < minTs || to.ts > maxTs) continue;
                const team = to.team === 2 ? 2 : 1;
                const color = team === 1 ? homeColor : awayColor;
                const x = PAD_L + ((to.ts - minTs) / timeSpan) * innerW;
                const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
                line.classList.add('set-chart-timeout', 'set-chart-timeout-line');
                line.setAttribute('x1', x.toFixed(1));
                line.setAttribute('x2', x.toFixed(1));
                line.setAttribute('y1', String(PAD_T));
                line.setAttribute('y2', baseY.toFixed(1));
                line.setAttribute('stroke', color);
                svg.appendChild(line);

                const badge = document.createElementNS('http://www.w3.org/2000/svg', 'text');
                badge.classList.add('set-chart-timeout', 'set-chart-timeout-badge');
                badge.setAttribute('x', x.toFixed(1));
                badge.setAttribute('y', String(PAD_T - 2));
                badge.setAttribute('text-anchor', 'middle');
                badge.setAttribute('fill', color);
                badge.textContent = t('chart.timeoutBadge');
                svg.appendChild(badge);
            }
        }
    }

    function formatElapsed(seconds) {
        const s = Math.max(0, Math.floor(seconds));
        const m = Math.floor(s / 60);
        const ss = s % 60;
        return `${m}:${ss < 10 ? '0' : ''}${ss}`;
    }

    // ── Set navigation ─────────────────────────────────────────────

    function switchToSet(setNum, currentSet) {
        if (setNum < 1) return;
        if (setNum === currentSet) {
            state.viewMode = 'live';
        } else {
            state.viewMode = 'frozen';
            state.viewedSet = setNum;
        }
        renderAll();
    }

    function wireNavButtons() {
        const prev = $('set-prev');
        const next = $('set-next');
        if (prev) prev.addEventListener('click', () => {
            const broadcast = state.lastBroadcast || {};
            const currentSet = (broadcast.match_info || {}).current_set || 1;
            switchToSet(Math.max(1, effectiveSet() - 1), currentSet);
        });
        if (next) next.addEventListener('click', () => {
            const broadcast = state.lastBroadcast || {};
            const currentSet = (broadcast.match_info || {}).current_set || 1;
            const best = Math.max(
                1, Math.min(7, (broadcast.match_info || {}).best_of_sets || 5),
            );
            switchToSet(Math.min(best, effectiveSet() + 1), currentSet);
        });
    }

    // ── Top-level render ───────────────────────────────────────────

    function renderAll() {
        const broadcast = state.lastBroadcast;
        if (!broadcast) return;
        renderRulesSummary(broadcast);
        renderAlerts(broadcast);
        renderScoreboard(broadcast);
        renderHistory(broadcast);
        renderStats(broadcast);
        renderSetChart(broadcast);
    }

    function render(broadcast) {
        if (!broadcast || typeof broadcast !== 'object') return;
        state.lastBroadcast = broadcast;
        // While in "live" mode the viewed set tracks the current set.
        if (state.viewMode === 'live') {
            state.viewedSet = (broadcast.match_info || {}).current_set || 1;
        }
        renderAll();
    }

    // ── WebSocket lifecycle ────────────────────────────────────────

    let ws = null;
    let reconnectAttempts = 0;
    let reconnectTimer = null;

    function connect() {
        try {
            ws = new WebSocket(wsUrl);
        } catch (err) {
            setStatus(t('status.error'), 'offline');
            scheduleReconnect();
            return;
        }
        setStatus(t('status.connecting'));

        ws.addEventListener('open', () => {
            setStatus(t('status.online'), 'online');
            reconnectAttempts = 0;
        });
        ws.addEventListener('message', (event) => {
            try {
                render(JSON.parse(event.data));
            } catch (_err) {
                /* ignore malformed frames */
            }
        });
        ws.addEventListener('close', () => {
            setStatus(t('status.offline'), 'offline');
            scheduleReconnect();
        });
        ws.addEventListener('error', () => {
            /* close handler will run; nothing extra to do here */
        });
    }

    function scheduleReconnect() {
        if (reconnectTimer) return;
        const delay = Math.min(15000, 1000 * Math.pow(2, reconnectAttempts));
        reconnectAttempts += 1;
        reconnectTimer = setTimeout(() => {
            reconnectTimer = null;
            connect();
        }, delay);
    }

    // ── Init ───────────────────────────────────────────────────────

    applyStaticTranslations();
    wireNavButtons();
    connect();
})();
