import { describe, it, expect } from 'vitest';
import { screen } from '@testing-library/react';
import LinksDialog from '../components/LinksDialog';
import { renderWithI18n } from './helpers';

describe('LinksDialog', () => {
  it('appends lang= to the spectator (follow) link', () => {
    renderWithI18n(<LinksDialog links={{ follow: '/follow/abc123' }} onClose={() => {}} />);
    const a = screen.getByRole('link', {
      name: /spectator|follow|espectador/i,
    }) as HTMLAnchorElement;
    // The spectator page reads ``?lang=`` to pick its UI locale, so
    // a share link generated by the HUD dialog must carry the
    // operator's active app locale (test helper defaults to ``en``).
    expect(a.href).toContain('/follow/abc123');
    expect(a.href).toContain('lang=en');
  });

  it('does not append lang= to control / overlay / preview URLs', () => {
    renderWithI18n(
      <LinksDialog
        links={{
          control: 'https://example.com/control?token=abc',
          overlay: 'https://overlays.uno/output/abc',
          preview: 'https://example.com/preview',
        }}
        onClose={() => {}}
      />,
    );
    const anchors = screen.getAllByRole('link') as HTMLAnchorElement[];
    anchors.forEach((a) => {
      expect(a.href).not.toContain('lang=');
    });
  });

  it('overwrites a pre-existing lang query on the follow URL', () => {
    renderWithI18n(<LinksDialog links={{ follow: '/follow/abc?lang=fr' }} onClose={() => {}} />);
    const a = screen.getByRole('link', {
      name: /spectator|follow|espectador/i,
    }) as HTMLAnchorElement;
    expect(a.href).toContain('lang=en');
    expect(a.href).not.toContain('lang=fr');
  });

  it('renders the "no links" fallback when nothing is shareable', () => {
    renderWithI18n(<LinksDialog links={{}} onClose={() => {}} />);
    expect(screen.getByText(/no links available/i)).toBeInTheDocument();
  });

  it('renders the read-only report links (locale-tagged) when present', () => {
    renderWithI18n(
      <LinksDialog
        links={{
          latest_match_report: '/match/m1/report',
          match_history: '/matches/index.html?oid=abc',
        }}
        onClose={() => {}}
      />,
    );
    const report = screen.getByRole('link', { name: /latest match report/i }) as HTMLAnchorElement;
    const history = screen.getByRole('link', { name: /match history/i }) as HTMLAnchorElement;
    expect(report.href).toContain('/match/m1/report');
    expect(report.href).toContain('lang=en');
    expect(history.href).toContain('/matches/index.html');
    expect(history.href).toContain('lang=en');
  });

  it('hides the owner reports link for unauthenticated viewers (no reportsUrl)', () => {
    renderWithI18n(<LinksDialog links={{ overlay: 'https://o/x' }} onClose={() => {}} />);
    expect(screen.queryByRole('link', { name: /all reports/i })).toBeNull();
  });

  it('shows the owner reports link when reportsUrl is provided', () => {
    renderWithI18n(
      <LinksDialog
        links={{ overlay: 'https://o/x' }}
        reportsUrl="/reports?oid=abc"
        onClose={() => {}}
      />,
    );
    const reports = screen.getByRole('link', { name: /all reports/i }) as HTMLAnchorElement;
    expect(reports.href).toContain('/reports?oid=abc');
  });
});
